name: odemisdev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cython>=0.23.5
  - decorator>=4.0.9
  - future>=0.16.0
  - h5py>=2.5.0
  - pylibtiff>=0.4.2
  - matplotlib>=1.4.3,<3.6
  - numpy>=1.13.0,<=1.23
  - nomkl
  - opencv>=3.2.0,<5.0
  - pillow>=3.2.0
  - pycairo>=1.10.0
  - pyinstaller>=3.6
  - psutil>=4.3.0
  - pyyaml>=3.11
  - pyzmq>=15.2.0
  - scipy>=0.19.0,<1.15
  - wxpython==4.1.1
  - setuptools>=39.2.0
  - shapely>=1.7.0
