# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcfr_main(wx.Frame):
#!XRCED:begin-block:xrcfr_main.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcfr_main.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "fr_main")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.menu_item_halt = self.GetMenuBar().FindItemById(xrc.XRCID("menu_item_halt"))
        self.menu_item_quit = self.GetMenuBar().FindItemById(xrc.XRCID("menu_item_quit"))
        self.menu_item_inspect = self.GetMenuBar().FindItemById(xrc.XRCID("menu_item_inspect"))
        self.menu_item_about = self.GetMenuBar().FindItemById(xrc.XRCID("menu_item_about"))
        self.pnl_main = xrc.XRCCTRL(self, "pnl_main")
        self.slider_stage = xrc.XRCCTRL(self, "slider_stage")
        self.btn_y_bp = xrc.XRCCTRL(self, "btn_y_bp")
        self.btn_y_p = xrc.XRCCTRL(self, "btn_y_p")
        self.btn_y_m = xrc.XRCCTRL(self, "btn_y_m")
        self.btn_y_bm = xrc.XRCCTRL(self, "btn_y_bm")
        self.btn_x_bm = xrc.XRCCTRL(self, "btn_x_bm")
        self.btn_x_m = xrc.XRCCTRL(self, "btn_x_m")
        self.btn_x_p = xrc.XRCCTRL(self, "btn_x_p")
        self.btn_x_bp = xrc.XRCCTRL(self, "btn_x_bp")
        self.slider_focus = xrc.XRCCTRL(self, "slider_focus")
        self.btn_z_bp = xrc.XRCCTRL(self, "btn_z_bp")
        self.btn_z_p = xrc.XRCCTRL(self, "btn_z_p")
        self.btn_z_m = xrc.XRCCTRL(self, "btn_z_m")
        self.btn_z_bm = xrc.XRCCTRL(self, "btn_z_bm")
        self.slider_aligner = xrc.XRCCTRL(self, "slider_aligner")
        self.btn_l_bp = xrc.XRCCTRL(self, "btn_l_bp")
        self.btn_l_p = xrc.XRCCTRL(self, "btn_l_p")
        self.btn_l_m = xrc.XRCCTRL(self, "btn_l_m")
        self.btn_l_bm = xrc.XRCCTRL(self, "btn_l_bm")
        self.btn_r_bm = xrc.XRCCTRL(self, "btn_r_bm")
        self.btn_r_m = xrc.XRCCTRL(self, "btn_r_m")
        self.btn_r_p = xrc.XRCCTRL(self, "btn_r_p")
        self.btn_r_bp = xrc.XRCCTRL(self, "btn_r_bp")





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    main_xrc = '''\
<?xml version="1.0" ?><resource class="wxButton" version="2.5.3.0" xmlns="http://www.wxwidgets.org/wxxrc">
  <object class="wxFrame" name="fr_main">
    <object class="wxMenuBar">
      <object class="wxMenu">
        <object class="wxMenuItem" name="menu_item_halt">
          <label>Stop all axes</label>
          <accel>Esc</accel>
          <XRCED>
            <assign_var>1</assign_var>
          </XRCED>
        </object>
        <object class="separator"/>
        <object class="wxMenuItem" name="menu_item_quit">
          <label>Quit</label>
          <accel>Ctrl+Q</accel>
          <XRCED>
            <assign_var>1</assign_var>
          </XRCED>
        </object>
        <label>File</label>
      </object>
      <object class="wxMenu">
        <object class="wxMenuItem" name="menu_item_inspect">
          <label>Inspect GUI</label>
          <XRCED>
            <assign_var>1</assign_var>
          </XRCED>
        </object>
        <object class="wxMenuItem" name="menu_item_about">
          <label>About</label>
          <XRCED>
            <assign_var>1</assign_var>
          </XRCED>
        </object>
        <label>Help</label>
      </object>
    </object>
    <object class="wxBoxSizer">
      <object class="sizeritem">
        <object class="wxPanel" name="pnl_main">
          <object class="wxGridSizer">
            <rows>2</rows>
            <cols>2</cols>
            <object class="sizeritem">
              <object class="wxPanel" name="pnl_tl">
                <object class="wxGridBagSizer">
                  <object class="sizeritem">
                    <object class="UnitFloatSlider" name="slider_stage">
                      <size>-1,16</size>
                      <value>100</value>
                      <min>0.01</min>
                      <max>1000</max>
                      <unit>μm</unit>
                      <scale>log</scale>
                      <accuracy>2</accuracy>
                      <style>wxBORDER_NONE</style>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <flag>wxTOP|wxLEFT|wxRIGHT|wxEXPAND</flag>
                    <border>15</border>
                    <cellpos>0,0</cellpos>
                    <cellspan>0,7</cellspan>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="lbl_py">
                      <label>+Y</label>
                      <fg>#E5E5E5</fg>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                    </object>
                    <flag>wxTOP|wxBOTTOM|wxALIGN_CENTRE</flag>
                    <border>5</border>
                    <cellpos>1,3</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="lbl_my">
                      <label>-Y</label>
                      <fg>#E5E5E5</fg>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                    </object>
                    <flag>wxTOP|wxBOTTOM|wxALIGN_CENTRE</flag>
                    <border>5</border>
                    <cellpos>7,3</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="lbl_px">
                      <label>+X</label>
                      <fg>#E5E5E5</fg>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                    </object>
                    <flag>wxLEFT|wxRIGHT|wxALIGN_CENTRE_VERTICAL</flag>
                    <border>5</border>
                    <cellpos>4,6</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="lbl_mx">
                      <label>-X</label>
                      <fg>#E5E5E5</fg>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                    </object>
                    <flag>wxLEFT|wxRIGHT|wxALIGN_CENTRE_VERTICAL</flag>
                    <border>5</border>
                    <cellpos>4,0</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_y_bp">
                      <size>40,40</size>
                      <label>▴</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <cellpos>2,3</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_y_p">
                      <size>40,40</size>
                      <label>▵</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <cellpos>3,3</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_y_m">
                      <size>40,40</size>
                      <label>▿</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <cellpos>5,3</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_y_bm">
                      <size>40,40</size>
                      <label>▾</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <cellpos>6,3</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_x_bm">
                      <size>40,40</size>
                      <label>◂</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <cellpos>4,1</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_x_m">
                      <size>40,40</size>
                      <label>◃</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <cellpos>4,2</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_x_p">
                      <size>40,40</size>
                      <label>▹</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <cellpos>4,4</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_x_bp">
                      <size>40,40</size>
                      <label>▸</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <cellpos>4,5</cellpos>
                  </object>
                  <vgap>7</vgap>
                  <hgap>7</hgap>
                </object>
                <fg>#E5E5E5</fg>
                <bg>#444444</bg>
              </object>
              <flag>wxEXPAND</flag>
            </object>
            <object class="sizeritem">
              <object class="wxPanel" name="pnl_tr">
                <object class="wxGridBagSizer">
                  <object class="sizeritem">
                    <object class="UnitFloatSlider" name="slider_focus">
                      <size>-1,16</size>
                      <value>10</value>
                      <min>0.01</min>
                      <max>100</max>
                      <unit>μm</unit>
                      <scale>log</scale>
                      <accuracy>2</accuracy>
                      <style>wxBORDER_NONE</style>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <flag>wxTOP|wxLEFT|wxRIGHT|wxEXPAND</flag>
                    <border>15</border>
                    <cellpos>0,0</cellpos>
                    <cellspan>0,0</cellspan>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="lbl_pz">
                      <label>+Z</label>
                      <fg>#E5E5E5</fg>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                    </object>
                    <flag>wxTOP|wxBOTTOM|wxALIGN_CENTRE</flag>
                    <border>5</border>
                    <cellpos>1,0</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="lbl_mz">
                      <label>-Z</label>
                      <fg>#E5E5E5</fg>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                    </object>
                    <flag>wxTOP|wxBOTTOM|wxALIGN_CENTRE</flag>
                    <border>5</border>
                    <cellpos>7,0</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_z_bp">
                      <size>40,40</size>
                      <label>▴</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <flag>wxALIGN_CENTRE</flag>
                    <cellpos>2,0</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_z_p">
                      <size>40,40</size>
                      <label>▵</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <flag>wxALIGN_CENTRE</flag>
                    <cellpos>3,0</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxPanel">
                      <size>40,40</size>
                      <bg>#333333</bg>
                    </object>
                    <cellpos>4,0</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_z_m">
                      <size>40,40</size>
                      <label>▿</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <flag>wxALIGN_CENTRE</flag>
                    <cellpos>5,0</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_z_bm">
                      <size>40,40</size>
                      <label>▾</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <flag>wxALIGN_CENTRE</flag>
                    <cellpos>6,0</cellpos>
                  </object>
                  <vgap>5</vgap>
                  <hgap>5</hgap>
                  <growablecols>0</growablecols>
                </object>
                <fg>#E5E5E5</fg>
                <bg>#333333</bg>
              </object>
              <flag>wxEXPAND</flag>
            </object>
            <object class="sizeritem">
              <object class="wxPanel" name="pnl_bl">
                <object class="wxGridBagSizer">
                  <object class="sizeritem">
                    <object class="UnitFloatSlider" name="slider_aligner">
                      <size>-1,16</size>
                      <value>100</value>
                      <min>0.01</min>
                      <max>1000</max>
                      <unit>μm</unit>
                      <scale>log</scale>
                      <accuracy>2</accuracy>
                      <style>wxBORDER_NONE</style>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <flag>wxTOP|wxLEFT|wxRIGHT|wxEXPAND</flag>
                    <border>15</border>
                    <cellpos>0,0</cellpos>
                    <cellspan>0,7</cellspan>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="lbl_pl">
                      <label>+L</label>
                      <fg>#E5E5E5</fg>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                    </object>
                    <flag>wxTOP|wxBOTTOM|wxALIGN_CENTRE</flag>
                    <border>5</border>
                    <cellpos>1,3</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="lbl_ml">
                      <label>-L</label>
                      <fg>#E5E5E5</fg>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                    </object>
                    <flag>wxTOP|wxBOTTOM|wxALIGN_CENTRE</flag>
                    <border>5</border>
                    <cellpos>7,3</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="lbl_pr">
                      <label>+R</label>
                      <fg>#E5E5E5</fg>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                    </object>
                    <flag>wxLEFT|wxRIGHT|wxALIGN_CENTRE_VERTICAL</flag>
                    <border>5</border>
                    <cellpos>4,6</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="lbl_mr">
                      <label>-R</label>
                      <fg>#E5E5E5</fg>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                    </object>
                    <flag>wxLEFT|wxRIGHT|wxALIGN_CENTRE_VERTICAL</flag>
                    <border>5</border>
                    <cellpos>4,0</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_l_bp">
                      <size>40,40</size>
                      <label>▴</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <cellpos>2,3</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_l_p">
                      <size>40,40</size>
                      <label>▵</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <cellpos>3,3</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_l_m">
                      <size>40,40</size>
                      <label>▿</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <cellpos>5,3</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_l_bm">
                      <size>40,40</size>
                      <label>▾</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <cellpos>6,3</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_r_bm">
                      <size>40,40</size>
                      <label>◂</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <cellpos>4,1</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_r_m">
                      <size>40,40</size>
                      <label>◃</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <cellpos>4,2</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_r_p">
                      <size>40,40</size>
                      <label>▹</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <cellpos>4,4</cellpos>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="btn_r_bp">
                      <size>40,40</size>
                      <label>▸</label>
                      <font>
                        <size>16</size>
                        <style>normal</style>
                        <weight>bold</weight>
                        <underlined>0</underlined>
                        <family>default</family>
                        <face>Ubuntu</face>
                        <encoding>UTF-8</encoding>
                      </font>
                      <XRCED>
                        <assign_var>1</assign_var>
                      </XRCED>
                    </object>
                    <cellpos>4,5</cellpos>
                  </object>
                  <vgap>5</vgap>
                  <hgap>5</hgap>
                </object>
                <fg>#E5E5E5</fg>
                <bg>#333333</bg>
              </object>
              <flag>wxEXPAND</flag>
            </object>
            <object class="sizeritem">
              <object class="wxPanel" name="pnl_br">
                <object class="wxBoxSizer">
                  <orient>wxVERTICAL</orient>
                  <object class="sizeritem">
                    <object class="wxStaticBitmap">
                      <bitmap>___gui_img_logo_h30_png</bitmap>
                    </object>
                    <option>1</option>
                    <flag>wxALIGN_CENTRE|wxALIGN_CENTRE_VERTICAL</flag>
                  </object>
                </object>
                <bg>#DDDDDD</bg>
              </object>
              <flag>wxEXPAND</flag>
            </object>
          </object>
          <bg>#333333</bg>
          <XRCED>
            <assign_var>1</assign_var>
          </XRCED>
        </object>
        <flag>wxEXPAND</flag>
      </object>
      <orient>wxVERTICAL</orient>
    </object>
    <title>FirstStep</title>
    <centered>1</centered>
    <bg>#000000</bg>
    <font>
      <size>9</size>
      <style>normal</style>
      <weight>normal</weight>
      <underlined>0</underlined>
      <family>default</family>
      <face>Ubuntu</face>
      <encoding>UTF-8</encoding>
    </font>
  </object>
</resource>'''

    ___gui_img_logo_h30_png = '''\
\x89PNG\x0d
\x1a
\x00\x00\x00\x0dIHDR\x00\x00\x00e\x00\x00\x00\x18\x08\x06\x00\x00\x00\xe3\
\xc03\xd0\x00\x00\x08\xd7IDATh\xde\xddZ\x09l\x94E\x14\xde\x1e \xca!\xc8\
%R4\x92piK\xefv\xb7\xedn\xdbm\xe9\xe1\xf6\x02z\xd1nKK[J[\x08\xb4\xa4 \x05\
\x03\x1eMJ\x0cE\x88\x8a\xdc\xe5T\xb6\x07\x02\x82GT\x8e\x04A\xa3\xd1\x10\
\x89\x04\x14\xc5\x88F\xa5\x04/\x04\x91\xad\xdf\xfb\x99\x99\x9d\xfd\xff\
v\xbbK\x9b\xc6M^\xe6\xdf\x997o\xde\xbc\xef\xc7\xcc\xaeF\xe3\xe2gGS\x93\
C\x9f\xc9d\xd2\xf4\xc4\x2733\xd3\xa1O\xaf\xd7\xbb%s\xf4\xe8\xd1N\xf3.Z\xb4\
\xc8\xa55\xf2\xabZ\xba=gZ\xeeN\xd76\x14\x19\x11a{\x8e3\x1a\x27\xe8\xa3\xa2\
\xe6FGG\x27\xf4\x04 \x90\xcd\xaf59*2\xb2\xca\xa0\xd7g\xdf\x0b\xd9\x81\x81\
\x81i\xfe\xfe\xfe[\xd0\x16\x83jA\xd5AAA\x09\x01\x01\x01\x8daaaA\x18k\xc2\
\xf7\xb1\xae\x01\xd2*\xb5yU-\xfe9\xf3\x9a-\xb9\x15\xcd\xaf\xabQN\x85\xa5\
\x0d\xed\xde\x92\xc5\x07|\xdd\xda\x10\x80\xc9\x8b\xd0\xe9:\xb4\xe1\xe1\x12\
\xc1Xu\x9a\x1e\xfa`\xad\xa7\xf8\xb5\xf0\xbd\xd1]\x99\xad\xad\xad\x1a\x18\
\xfdE??\xbf\xab\x00\xe1\xd0\xd4\xa9S/\x80\x8e\x02\x84\xd7\xd0\xf7Gpp\xf0\
z\xb4V\x00\xa55\x18\x0c\x9e\xdd\x91mf\x1e\x02`\xa6d\xcd\xdd\xd7\x91Y\xd6\
\x19Y\xae\x01\xb4u{v\x9d\xf1p\xcbS\xe8\x03\xe3\xd4\x90\x81tZ\xad\x95\x81\
\xb2\xac\xa7@\xc1\x1a\xb3\xf8\xb5\x00\xca\x9a{!\x17\xde\xd0\x1f4\\\xab\xd5\
\xde\x1f\x13\x13\xd3\x1f\xe0\x90g\x94\x02\x9c\xf7CCC3\x00\xda\x17\x00\xa7\
\x18\xdf\x0fb\xcc)\x8f)X\xd0v\xc7C*\x9b\x27d\xcd\xb5\xb4\x93\xe1\xd1ZAR\
+\x83\x91]n9\x0b*1W\xb5\x8d\x90\xe7.|\xe6\x88{\x1b\xc2F\xaaa$2TG/\x80\x92\
\xcb@\xe9\xb8\x97\xa0\x88\x1f\x80p\x0c\xa0\xac@{\x19\xa0T\x00\x8c[\x00e\
\x15<\xe6/\xf4O\x82\xd7xu\x1a\xb2\x18 E\x0b\xdb\x1e\x02\x007e@$ $\x8f\xb1\
\xdc\x06\x10?\xe7V\xb4\xa4\xd8\xe6\xcco\xbd\xa7\x86\xaa\xd6\xfe\x8f@\xf1\
\xf5\xb5\x0f\xe7:\x9dn\x0c\xc0\xf9\x0c`T\xa2=\x05OYC\xe1-$$d\x98\xd2\xfc\
\x92\x9a\x03R;\xab\xb2e\x1c\x80\xb8\xcc\x03B^\x020\xde\xcc\x99gI\xd3\xf4\
\xe4G\x02\x853\x943\xa0\xb4\xb6\xb4\xf4IP\x8e\x1c>\xec\xd0g4\x1a\x07\x00\
\x8c\xd3\xf0\x94t\xb4\x9f\x00\x9cj\xb4\x27\x90_\xfa\xd18\xbcG\x93\x9e\x9e\
n7g\xe3\xaeO=\xb3\xe7Z~\xe4s\x06\xf2\xc5\x07\xf0\x06\x9f\xac\xb2}6\xbe\xc2\
\xc2"\xbby\xb3\x0b\x0b\xbbV2\xc6`\xb0=\xa3\xd2\xd1\xc2\x08E0\xfaR$\xdbe\
x.GE\xa4\x87\x81\x96w\x07\x94\xf8\xb8\xb8\x91\xe0I\xc1\xfc\xf9\x90S\x87\
\xe7%LndYi\xa9\x14\x16\x02\x03\x024\xb9\xd9\xd9\xdd\x06\x05\xb25\x90\xf9\
$\xc6\x12\xc0\x93XS]-%\xcdh\x83a<\x15$ Z\xab\x0eT\x01JN\x986m\x88<\xb7\xa3\
\xa3C\x13\x85\xfd@\x8f2\xc6C\xbcf\xec\xfb\x09~\x0dx\xca
x\xcay\xb4\x07\xd0\x9e\x95\xfb\x8b*7\xc8ah8\xbc\xe1<\xf3\x8c+x\xde\x94\
W\xd5\xea\xc7\xcbHMI\x19@\xfb\x85\xfc\x02\xd0b\xd0
|\xa7v\x16\xd6\xf3\xef,\x81KmlLL 6z\x11\x9b\xbc!\x27X\xd90\xa0\x9b\xd4\
\xdf\x19(\x0d\x0d\x0d\x9aq>>\x9a\xd2\x92\x12/,\xba\x99\xc9\xb9%\xf3\xcb\
\x89\x9b\xc9\xba\x02\xa5\xf2]\xf5\x14\x06\xca\x16\x8c\xfd\xc3tY\x0e\xaa\
\x01\xff\x9f\xa0\xdb\xf2<\xa6;\xe9p\x1d/\xd6\x82\x98\xe8hz\xb9~e:\x88z\xdd\
\x80\xccV\x00\xe8Mk l\x85#\xa7\xd4\xc3c2A\xf3m\xe7\x9d\xb1\x93\xa4\x16 \
|I\x95V\xee\xbc\xe6\xbaY\x15\xcd\x0f\x96\xd7\x1e\xf0\xe0u$\x9d \xf3\xaa\
\x8a=I\xc7\xbf\xb1\xdeY\xd8}\x8a\xdd\xe6\x0d\xec@\x06\x01\xb5\xbc\x82\xf2\
\xb3Hj\x89>$8X\x967\x19\x0b\x9d\xebJ\x0eW\xean\xd9\xb3{\xf7\x9d\x18=gNw\
A\xd9\xee\xcc:l\xdc*\xea/\xf20\xa2\xb5\xdePzQ\x10\xbe\xce!\x9c\xbd\x0bO\
\xf3B\x88\xda\x09PV\xaf\\s\xdcV\x08\xc0\xb8\x1a\xe6\xad\x8fB\xb73]\xed]\
\xd6\x07^{7\xef\xc4\xc5\xc6\xca\x87\xb5RYYy\x83\x10\xfa\x0b\xfaW\xc2\xc8\
\x19\xa0\x1c(\xba_\x1eW\xf3\x14(3\x11c\xed\xbc\xa1 \xe7\x12\xe4TB\x86\x01\
o\xa9\x09s\xd6\x8bFA\xdf\x0e\xa9\\\x0d\x0du\x1b\x14\xf0]\xc2Zf\x1clc!\xb7\
\x9ey\x89\x95\xf3\x1c\xb9\xc4\xde\x0d\xbex\x90\x09\xcfo\x8br\xd0o\x97\xa0\
\xe1)D\x91\xf0\x9e\xf1K\x1b\xdb\x1f(^\xfa\xf1@[8[\xd8f\xe3KOK\x1b\x08\xbd\
\xae\x8a\xf2\xa0\xcbf\xc8L\x85\x8d\xf4h)\xbc\xb6\x91N\xe0=\xd2P_o\x8f>N\
\xcc\x8f0\x85mo\x12&lTzS `\x95R\xf8\x82\xbb\xcb\xe3\xfb\x05@\x0e\xa9\xe4\
\x1a\x1f
_\xf2\xdb\xc9\x8c\x10\xeeB\xf8\xda\xce\xf3\xe0{\x9b\xb8\x16\xe4f\xf2:\x11\
/^\x8eT\x85\xc3\xeaVa\xbd\xb7\x84P\xe4\x09\xf930V\xcc\xa8\x14\xb2\x07\xf0\
<\x94\xab\xc0\xf3\x0e\xe7y\xd4^LLH\x18\xa3d\x07xV\x9016v\xac\x92\xa1_\x16\
\x0ciS&\xdeh\x14s\xcf"\xb5\xf0\x95\x94\x98\xf8\xb0]\x8c\xd6\xe9nohl\xf4\
P\xcb\x19Xg\x85`\xd0\xb5\xee\x82\x82v\xbaJ~\xb2\xe9\x859\xed|\xd8\xe6\x8c\
n\x00\xdf\xbf\x9c\xac\xaf\x84\xf1\xfe\xe4\xf5\xfcz\x901R\x1eOKM%\x9e\xc7\
1\xf6;\x17
o J\x84\xf1\xa1M\xcc\xe3b\x91E\x8c\xf7a\xe2G\x1c\xaaV\xd4\x09\xf9\xae\x1c\
\x1e\xb1\xf8\xd3\x82\x11OP\xb8\x82\xbb\xceT"l\xe8Y.\xc6[\xb1\xe1\x83xk\xbc\
\\\x05\x85\xf1\xcdP)dx\xf0\xdb\x15\xab\xcf\xe8h-K\xc8\xb2\xbcs\x02(\xfd\
0\xf7k5P\x98\x0dL\xc2Z\xdft\xbbV\xc7BC \xe0\x02\xa7\xc8m,\x14\xe2\xca\xe1\
\x11\xcfm\xbc\x91\x9dLr\xf2\xcb \xc5V\xb7@\xb9#s\x86\x9a\xa7\xf4\x06(Tm\
\x09:ou\xe56v(\x16\xfaN\x00\xc5\xcf\x15O\xe1b\xa9l\xf0[l\x93N\x11\xe6\xbf\
ZV^\xae\xe9\x09O\xe9-P`\xcfz!\xe7\xaes\x05\x94\xc1\xb48\x0f
\xfa\xe2\\\xf4\x94m\xbcB\x90\xb3\x16o~(Bd\x843D\xc9\xdf\x9d\x9c\xd2\x17\
<\x05{\xae\x12t~\xaf\xfb?\xae\xc4\xc7\xd3B\xc7\xf8\xb0\x03A\xf5t^\xf0\xf3\
\xf5\xd5d\x08W
\xe0S\xf5\x14(\x98\xcb\x87&\xc8=\xad\xb6\xae\x91\x95\xe2\xd2<>\xc9\xb9\
\x03J\x1f\xf0\x14\xf0\x84\xf2G\x0b\xd0\xb5\x14\x93i0+\x84Tm\x00\xb9\x0e\
\xa5\xe0\x0bB\xc9\xf8\x1b\x16\x8bQ\xd9\\\x8d\xda\x89~zFF?:5\x0bW\xfb\xaa\
?\xdf\xe5dg\xf7\x83!&H\x06\x8e\x8fw\x06\x94W\xfa2(\x85\x05\x05\xf4b\x0e\
\xc7\xd8e\xbb\xc2)"b\xbd\x9a\x0dV74x\xa0\xe8q\xcc\xe1\xd9YY\x03\xc4\x83\
\x15\xe5\x03\x08;\x88\xb0b\x84\xb1\x87\xa2\xdc\x1b\x05\xd7\xac%\xc0\x94\
@A\x1dN\x9b"\x80\x9f\x13\x13=\xfaNb,\xa9\xc0l\x1e\x84:\xde#9)\xc9\x07\xb2\
\xe6\x81\xe7{l\xf2\x87NJf\x11\x94\xcf\xbb*\x89U\xab\xaf^\xf2\x14\x89/*j\
\xb9xp\xc4\xbco\xe9\xc0\x98\x9e\x9e>\x82\xce2\xb0\xe7\x18\xba\xf2A?]\xf7\
\x9c\x81\x9d\x07\xdam\x8c\x9d\xc4\xf5\xdc\xbd\x96\xb5\x8bk\x16\xd5\x13=\
N\xb3\xdeT\xda\x8a wB\xf4&\xcd\x17kxf\x84D!\x14\\G\x9fiIm\xadG_\x0d_C\x86\
\x0d\x93\xa3\xcf&gm ]\xb3DF\xceT\xbc\xfb\x020~t\xb5\xa2`|\xfe\xce\xe8\x27\
\xe1z\xa4N\x94\x83X\xe9\x8d\xfe\x12\x85\xcb>\xbb;(Y&]\xf1\xc8/\x87\x10
\x1ee\x9ei\xe5=85%e\x10\x07J\x93\xb0\xc9\x99j\xe7\x14n\xcdkJ<\xd8?\x81\
r\x8b\xe3\xbb\xa0\x00\xcaE^\x96\x08
\xa2\x80\xd4"\x17{`_\x99t\x18\xb5\xbb\xb3\xb7\x83\xad_\xf1\xff\x07\x14\
z\xb8
b:\xdd\x0b\x81\xf9\x04%k\xb4\xc7\x09y(\x1d\x811\x1d\x95y\xa05\xa0F\xf4\
9Tj\xb1,\x81\xadml\xf4$\x83c\xae\x85\xc9:\x85\xf6$\xda\x0f\xd1\xb7\x0dc\
\x05\xe4\xca\x9d}\xe8n
\xfcG1\xef\x14\xdd\xdeB\xcf\x89r\x0e\xa2\xab\x1d*.\x98.D/\x81\xfcT\xce\
c\xeb8\xbe\xe7U\x8a\x8f\xc70\xb6Z\xe6\xa3\xc3\xb0\xa0\x8b\x17\xfa\xea89\
\xeb0g\xa0\x92,\xf9r\x96\xfd\x03\x27\x17\xfb\xddIvd6\xa0\xc3\xfa1\xf4\xed\
\x85\xbc9\x14\xd2\xd5g6\x9b\x1d\xfa\x8a\x8b\x8a\xbc\xbb\xaa\xe0\x92\x93\
\x93\x1d\xfa\xe2\x84\xeb\x192\xfe\xec\xc2Bo\xb3\xd9\xec\xa9P\x01*\xca\x0d\
\x0f\x0b\xbb\xfb\xa7\x84\xfc|/5\xd9
\x00t\xfa\x9d\xc5}\xa7\xaa\xd3Q#Ft\xc9cP\xf9\xdb\xd3\x8c\xe9\x8e7>\xf9\
yy^\xb0\xb3\x97\x92\xbd\xfe\x03\x88R\x00z\xf4\x93\x13\x0b\x00\x00\x00\x00\
IEND\xaeB`\x82'''

    wx.MemoryFSHandler.AddFile('XRC/main/main_xrc', main_xrc)
    wx.MemoryFSHandler.AddFile('XRC/main/___gui_img_logo_h30_png', ___gui_img_logo_h30_png)
    __res.Load('memory:XRC/main/main_xrc')

