# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcfr_main(wx.Frame):
#!XRCED:begin-block:xrcfr_main.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.

        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass

#!XRCED:end-block:xrcfr_main.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "fr_main")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.scr_win = xrc.XRCCTRL(self, "scr_win")
        self.fpb_settings = xrc.XRCCTRL(self, "fpb_settings")





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    main_xrc = '''\
<?xml version="1.0" ?><resource class="">
  <object class="wxFrame" name="fr_main">
    <object class="wxMenuBar">
      <object class="wxMenu">
        <label>File</label>
        <object class="wxMenuItem">
          <label>Hello</label>
        </object>
      </object>
    </object>
    <object class="wxFlexGridSizer">
      <object class="sizeritem">
        <object class="wxGridSizer">
          <cols>2</cols>
          <rows>2</rows>
          <object class="sizeritem">
            <object class="wxPanel">
              <bg>#D9B0BF</bg>
            </object>
            <flag>wxEXPAND</flag>
          </object>
          <object class="sizeritem">
            <object class="wxPanel">
              <bg>#E5C19C</bg>
            </object>
            <flag>wxEXPAND</flag>
          </object>
          <object class="sizeritem">
            <object class="wxPanel">
              <bg>#ACA8EC</bg>
            </object>
            <flag>wxEXPAND</flag>
          </object>
          <object class="sizeritem">
            <object class="wxPanel">
              <bg>#A8E876</bg>
            </object>
            <flag>wxEXPAND</flag>
          </object>
        </object>
        <option>1</option>
        <flag>wxEXPAND</flag>
        <ratio>1</ratio>
      </object>
      <cols>2</cols>
      <rows>1</rows>
      <growablecols>0</growablecols>
      <growablerows>0</growablerows>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <object class="sizeritem">
            <object class="wxScrolledWindow" name="scr_win">
              <object class="wxBoxSizer">
                <orient>wxVERTICAL</orient>
                <object class="sizeritem">
                  <object class="odemis.gui.comp.foldpanelbar.FoldPanelBar" name="fpb_settings">
                    <XRCED>
                      <assign_var>1</assign_var>
                    </XRCED>
                  </object>
                  <flag>wxEXPAND</flag>
                </object>
              </object>
              <size>300,-1</size>
              <style>wxVSCROLL</style>
              <XRCED>
                <assign_var>1</assign_var>
              </XRCED>
            </object>
            <option>1</option>
            <flag>wxEXPAND</flag>
          </object>
          <object class="sizeritem">
            <object class="wxButton">
              <label>Self Destruct</label>
            </object>
            <flag>wxALL|wxEXPAND</flag>
            <border>10</border>
          </object>
          <orient>wxVERTICAL</orient>
        </object>
        <flag>wxEXPAND</flag>
      </object>
    </object>
    <size>1200, 800</size>
    <title>Odemis</title>
    <centered>1</centered>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/main/main_xrc', main_xrc)
    __res.Load('memory:XRC/main/main_xrc')

