#!/bin/sh
# This script exports all PNG files in the current
# directory into a Python module called data.py

first=1

rm data.py

for file in `ls *.png`
do
    if [ $first -eq 1 ]
    then
        img2py -c -f $file data.py
        first=0
    else
        img2py -c -a -f $file data.py
    fi
done
