#!/bin/sh
# This script exports all PNG files in the current
# directory into a Python module called data.py

first=1

rm data.py

# I hate bash scripting with a passion
if [ $# -gt 0 ]
    then
    echo "Optimizing PNGs"
    pngcrush -brute -rem alla -d tmp *
    mv tmp/* .
    rmdir tmp/
fi

echo "Building data.py"

for file in `ls *.png`
do
    if [ $first -eq 1 ]
    then
        img2py -c -f $file data.py
        first=0
    else
        img2py -c -a -f $file data.py
    fi
done
