#----------------------------------------------------------------------
# This file was generated by /usr/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

catalog = {}
index = []

arr_down = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAMtJREFUeNpi/P//PwMlgHHADWAYVAawAfEWkBAB/AuIdUHe"
    "RzeAB4h9gfg3AQOWAbEkEDOjG8ABxNoEXPEBiL2BWBibCxihEt5QhdgMmATEykDMiisQWaEK"
    "JmHR/BCILYCYD247FgMYoQpACu+gGVAJxDJwv+OJRmaownwg/gvVfAKIjYCYi9h0wAnE+kB8"
    "BIh/AHE0EIsDMROxBoAUigFxGBDPAmINIGbHmRcYGRmxyYE0iEKj9w0Qf4R6h+ikzAiNFZAB"
    "LLgUAQQYANzNZsqvm8moAAAAAElFTkSuQmCC")
index.append('arr_down')
catalog['arr_down'] = arr_down
getarr_downData = arr_down.GetData
getarr_downImage = arr_down.GetImage
getarr_downBitmap = arr_down.GetBitmap

#----------------------------------------------------------------------
arr_right = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAANlJREFUeNqs008LAUEYx/Edf8PJzV3egZsXoLwAuShXLvKK"
    "HJzkKHkBDnJWDkoKF0WSKML6To0aW5g1pj617e78ep59ZoXruo7NCjiWyzrA+WcL8jqHIoK/"
    "VBBBWd7CEFmjFrWAGGoqQLqhiRSESQvypbDnWQVTNBD9VkEcda0CLxlU8LblZ4wZdFHSP7Kf"
    "gAmqGOj7QgYbt+ighzkOuJsEXNBHGzOssMPZJGCEFsZYYoOTGu3LEnIKQojnOcgjrTYusFYl"
    "X9+VqQfIM5BEAkfsVRsff5aHAAMAKrxD0QPtM2sAAAAASUVORK5CYII=")
index.append('arr_right')
catalog['arr_right'] = arr_right
getarr_rightData = arr_right.GetData
getarr_rightImage = arr_right.GetImage
getarr_rightBitmap = arr_right.GetBitmap

#----------------------------------------------------------------------
arr_s_down = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGBA0dBrfdTnkAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAMklEQVQ4y2NgGAXDDKQxMDD8"
    "JwGn4TMEH8CpmRhDCGrGZwjRmrEZQrJmdEPSKI2dQQwA5FgZGxaMtPkAAAAASUVORK5CYII=")
index.append('arr_s_down')
catalog['arr_s_down'] = arr_s_down
getarr_s_downData = arr_s_down.GetData
getarr_s_downImage = arr_s_down.GetImage
getarr_s_downBitmap = arr_s_down.GetBitmap

#----------------------------------------------------------------------
arr_s_right = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGBA0dOHa8U9IAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAN0lEQVQ4y2NgGOwgjVID/lNq"
    "yH9KDflPqUv+U+qd/5SGyX9KA5aqLqAoDCiKBYrTQdqA5gWCAABDZRkbE+EX3wAAAABJRU5E"
    "rkJggg==")
index.append('arr_s_right')
catalog['arr_s_right'] = arr_s_right
getarr_s_rightData = arr_s_right.GetData
getarr_s_rightImage = arr_s_right.GetImage
getarr_s_rightBitmap = arr_s_right.GetBitmap

#----------------------------------------------------------------------
btn_big_a = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAFAAAAAsCAYAAADy8T8XAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAvZJREFUeNrsm8uKGkEUhkstr3hjFF1koYLuA4E8gLjLNpBF"
    "9oFZZ5N19sl2lgmEzCqQJ0geIE/ggAgOBBxdeAveW1N/k9NT03Z3FIQE6hz4qW67Vh9/nVOn"
    "KEOtVkuEQiExGAwuhBCXSs+UYoLDKyyl70pXpVLpdr/fCxkOh8Xd3V1TQfyWTqdFKpWygZI4"
    "hAAo0mKxeDqbzd4ow70sl8vX8g+ky0KhIAAQQCH8jhFhKkgAo3G329ljMpm0pQB+Vsb7Ivv9"
    "fjORSDzP5XIiEok4ckM02X2AR7IsS0gp4UQxnU5fSbgvn8+LWCxmfyCRE011odt9AAdtNht7"
    "zGazAPgCAJ9kMhmhXCii0agtgggnEjiTARK87XZrA1yv1wLMVDwGwAvAgwPj8bg9EkRayiYD"
    "JPcBHuRikgZAGxjgkXQXmp4DdYBwHoxErgQbByAE95ETdQeaXIWpeGDpEge8AyjCBghQAEYQ"
    "6ZkdeA+LnEfvYOMAtK2oVWBypL7eTQZIzgMTLF3a6j0A6CW9Cpsa5DywoLynG0vSpCCZHkFc"
    "wkFbFCrlDNDfRFJvlv0aaD5I8Gch3btuLzFAfybSq3XRJzFAb3g0/tWBpoebg6cD3Uc2ukyv"
    "wm42+vtBEWEHHp8DD5YwAzwtBx4UEc6BZ3DgMfseBugD0CtJchHxL7APAPIm+vROJHAf6Nfe"
    "McATqjB3IcK3M/PNgV75j3PgETmQ94HcC//bHMhV+LQq7HmYEJQoGSD3wmc5zmKAZz5MsC9Y"
    "HrvzZoC8hBngf92J6N2I/s43VPe+EAngL8uycryZDgaot7pae2cB4M1yuXyEG5fufhh9sOln"
    "gvqq1J8VM3y+AcBPo9GoiVv6XsuY3XcoMJpMJpjyFQCvx+Pxh/l87lzforyHyXy9befcCSSt"
    "VisxHA7x+UpWKpV1r9d73el03tVqNVEsFp0lywDvL5kDHEY4r9vt4vlttVr9KfFjvV5/rwDe"
    "tttt/NWrKTiC4gec12g0PiIP/hZgAAIhHv6p1BzdAAAAAElFTkSuQmCC")
index.append('btn_big_a')
catalog['btn_big_a'] = btn_big_a
getbtn_big_aData = btn_big_a.GetData
getbtn_big_aImage = btn_big_a.GetImage
getbtn_big_aBitmap = btn_big_a.GetBitmap

#----------------------------------------------------------------------
btn_big = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAFAAAAAsCAYAAADy8T8XAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAihJREFUeNrsmz+r2lAYxt9oUFujwUV0cJTrpC5Wv0ChSztd"
    "uLtDoaUXnFzcOjg4eguufoZioF9AcMxU6Ko4iUM1Go3/mifcFKFe9bZbeX5w0BMz/Xjec2J4"
    "j2IYhqiqKvV6/Z2IfHDHGyHnMNzRabVaxna7FaXX60mj0fikadpDtVqVfD4viqJQ0wkOh4OY"
    "pindblcsy/rYbDY7SqFQ0EKh0LxWq0k6nfZu2u/3tHWCQCDghWs8Hku73RbHcWIqyrZcLouu"
    "6zKfz2W9Xstut6OtEwSDQQmHw5JIJKRUKkm/338PgbfZbFZs2/aSR3lPgzUPFYok5nI5CLyD"
    "wJt4PO79SC6DkGHEYjFMbyBQxzckj5vHdRsJxiO66stDLFHj5DLw5S916rHVI7PkyhRSIAVS"
    "4P8h8PiTXCeRCWQJUyAFUiAF/rtA/w8yed4LBSaQJUyBFEiBjxe4iTxvE2ECWcIUyAdpPkgz"
    "gSxhCqRACqRACqRACqRACvx7geg08juz2OJ2Wd5xIyoEWrZtaxCHbn22uJ0H4tCMulwuMf0J"
    "gd8nk8mrZDIpkUjE6xMkT7PZbGS1Wsl0OsX0RzCVSgXcSL6NRqPeDUggU3gax3FksVh4Yzgc"
    "IoWfcczhhZu6ZSaT8RLIMj5fvkggTjKMRiOshS/VSqViDwaDe/fCg6Zpv1/XkD/xlzfLsuDo"
    "Hu68XbhYLH4xTXM8m81w1Os1VZ3lmzs6rrOvmPwSYADgQ3VDpXdADQAAAABJRU5ErkJggg==")
index.append('btn_big')
catalog['btn_big'] = btn_big
getbtn_bigData = btn_big.GetData
getbtn_bigImage = btn_big.GetImage
getbtn_bigBitmap = btn_big.GetBitmap

#----------------------------------------------------------------------
btn_contrast_a = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAEQAAAAaCAYAAAAOl/o1AAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGGwgtOKdL4AMAAAPT"
    "SURBVFjD5ZnBSytXFIe/mbmZKBgliAoWGks0KIHZiEJXIrgoVJfZ6saNVejav8Bd6ULrXreB"
    "BORtRAxC6EJwExgUXSuVLDQJ0onJTLp5d95NMnk2UJqQd+AwyczcuXe+/O45595ofLZkMvkT"
    "sAN8x7dlfwHHtm1/AtA+w/jdNM1fR0ZGMAwDXdcB0DRtIAk0Gg0APM/D8zze3t5wHOfYtu1f"
    "tGQy+aNpmn9OTk76MDRNa/JBg6G6hFIsFnEcZ10AO5FIhFAohGEYPhQVzKACcV0Xz/Oo1+tE"
    "IhEcx9kRwA/hcBjTNBFCDDSUVlW4rovruui6TjgcBvheAAghME2TUCjkQxFCDDQQCaNWq6Hr"
    "Ou/v7wAIAMMwCIVCmKbZpBSpkk4Btlqt8vDwQKlUajo/NjbG3NycpN6XgdTzPB+GpmkIIb4A"
    "kQqRriqlkzqur6+5urqiWq0GXr+8vGRlZYXl5eW+U4nrutTrdV/9jUYDwzC+ANF1HcMwfBgq"
    "EKkQ1XK5HLlcru387u4ulUqFTCZDpVLh/PycWq3G6upq3wDxPK9J+QCu6wYD0XUdIYTvahqW"
    "dnNzEwgDYG9vzwdzdHTEyckJuVyO8fFxFhcX+wqInBkShn9OxgdJTbrMNmpQfXl5IZ1Of9jp"
    "6Ogo+/v7lMtlstks6XSa2dlZotFoz6eLruv+FPE8r20W6BJIJ1czTT6f72oABwcHLC0tAZDP"
    "57/az//h8l1aVa+arkbgjwoZ27a7/lU2NzcBsG27rUrshQeZCkeoc6vTQ9Qp062tra35bb8G"
    "vhepNwiUUGGolZtaf/xXhZnneX1RmMn3VCtWCUXIGyUU9di6wBsaGsJxnK4G8fj46LftFyDq"
    "O6pKaQIStApsBTIzM8Pd3V1Xg8hkMn7bfgPSurZpU4jqQVsA8/PzXQG5vb3l6OjIb9tPQILU"
    "0ZRlWm8OgmRZFrFY7F91fnFxwdbWFgCxWAzLstqe1ysPercmhQTFD6kSNcsApFIpTk9PeX5+"
    "7hgzDg8PyWazAExNTZFKpXqujk4LvMAY0imOSBiqpMLhMNvb25ydnVEoFJo6XFhYaPpuWRYb"
    "Gxt8VOv0aoMoCFZbDGlVSKe0u76+TiKRoFAocH9/33QtkUhgWRaJRKJvQHSKITL9qnVISeZl"
    "tQ5xXffDOiQejxOPxzsOQD6j34BICOqxVqsBlARw+vr6+nM0GvUvyqJMLoYGyVq3D+XncrkM"
    "kJZ/Q/wxMTGxMz09zfDwcNPyfxA3meUGUb1ep1qt8vT0JJNEWAbV/WKxWCoWizvAGN+W/Q0c"
    "A7/Ztv3+D6NP8KFCucV4AAAAAElFTkSuQmCC")
index.append('btn_contrast_a')
catalog['btn_contrast_a'] = btn_contrast_a
getbtn_contrast_aData = btn_contrast_a.GetData
getbtn_contrast_aImage = btn_contrast_a.GetImage
getbtn_contrast_aBitmap = btn_contrast_a.GetBitmap

#----------------------------------------------------------------------
btn_contrast = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAEQAAAAaCAYAAAAOl/o1AAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGGwc5MIxi+FkAAAMX"
    "SURBVFjD5ZixSyNZHMc/kxkSTXOisQgrBypIGISBGZutLD3YLRLQNqTNFWpjsZX6DxzB4rYK"
    "RA5s3GKaBU0buEIwTEAsUkhAi4MkOENwFIeZ2cYJcd2sk+JYh3zh17zhzcz78P39fu89gScp"
    "ivIHUATeMV76D/jcaDS+AkhPMErz8/NbuVyOVCo1VjRub285OTn58ATlT0FRlPdzc3P/7uzs"
    "MDExge/7YwVEEAQcx+Hg4IBms/lRAoorKytYlkWv18NxHDzPGxsYoiji+z6qqtJsNosSMB+P"
    "x+n1esRisbF0iOd5SJIE8LsE4LoujuMEg6Fk2zbn5+e02+1n47Ozs2iaRjKZjAwU13VxXZd+"
    "UfU8rx9hdHp6iq7r2Lb9w+fJZJJsNsva2lokgAyuXQLwfb8fr0nXdXRdfzG+u7uLaZpUKhUs"
    "y+Lo6Ajbtslms28eyODaY8HAoEuGRa1W+yEMgL29PUqlEq1Wi62trT68Wq0W6t2/OgIgoVOm"
    "2+1SLpdfpT01NUWpVMI0TQ4PDymXyywtLTEzMxOJlAntkGq1OtJHKpUKq6urAFSr1cg4JPa9"
    "Q4aFYRgjk9/e3gbAMIxIpM2zohomZUZVUFC73e6b3uy9ABJY5v/86bcO5FlR9X2/vzEZpsnJ"
    "Se7v70f6UKvV6s997f2/emP2wiGe5yEIwtBJi4uLXFxcjFxYg7mRSpkgXX4GZHl5eSQghmGw"
    "v7/fnxuplAnjEE3TODs74+rqKtRutlAoALCwsICmaZFxSOi263ke+XyedDr905pRKBTI5XJY"
    "lkU6nSafz0ei5Y6cMgCJRILNzU2Oj4+p1+svjtGDUlWVjY2NN99hhnaZsIc7gPX1dWRZpl6v"
    "c3l5+eyZLMuoqoosy5G5Wxlce7+GBG3xNZcEymQyZDKZSO47vocxuH4JsO7u7nh4eCAejyOK"
    "YmgoUVcA4/HxMbjbsSTgn+vr6w+JRAJRFInFYmMDZNDJNzc3AF8EAEVR/k6lUsXp6WkEQRi7"
    "e1XTNGm32/i+nwguUT91Oh2r0+kUgd8YL90Dn4G/Go3G4zeVyStzf4jFIwAAAABJRU5ErkJg"
    "gg==")
index.append('btn_contrast')
catalog['btn_contrast'] = btn_contrast
getbtn_contrastData = btn_contrast.GetData
getbtn_contrastImage = btn_contrast.GetImage
getbtn_contrastBitmap = btn_contrast.GetBitmap

#----------------------------------------------------------------------
contrast_label = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADIAAAASCAYAAAAZk42HAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGGg8FLrMxihgAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAACLUlEQVRIx+2WP2gUURDGfxeC"
    "YHWIoAiSRBGsxMr6rks13h2klSMg/teNCrbL2dgEIaCFjdlYaCBFFkasFSy0kFywi8E7NNgI"
    "nilsAvJsZsNz7/a8NQQu4gePZWbezHvfm9l5D/4RFDL0RaAKTKT0bSAGNvcCuQDoAC5jdGzO"
    "UCPstfkwDF0QBK5YLPr6cFhJ1LOykKDT6bggCHxbfdhIjPcpJZdGvV737eP9AovIpIg4EZnM"
    "syER+ZJn/oh9Z/I4RVFEqVRiQN8AeATcyHm4R/6ma7V6dKhtOOe6dHEcU6vVkk52LONUTwKv"
    "gDFgFaio6ppnd6pa6CWLyG+LqmpBREaBu8BlUz8EQlX9OWqKiby1WK1WGcD3FvBMVbdE5IFl"
    "5+qga/gkDbeBM8Apk58AN4HZkd366UTkIHAOiJKKBM6KyIEdhJ0GAlXdUNUNK9fz/j/yPW/E"
    "drvNH3wvAGuqumqn+wN4ClzcAZEx4KMnr5tum8jLvBGjKDnobl+r5SvAaetYzmr+DnDN7ACb"
    "IrI/Y4ktEdmX0n0GjnvyCeATQBIwtifJQGg2mzQaDTzfNKaAw8AhVf2aIrlk9kXgNVAzXZrQ"
    "OlARkefAUVX9YOU5JyLTNmcOeOxnZGHQrMRxTLlc9rOx0GPaDPAiTcJw32vZ14FL9nZrA29T"
    "jeIe8C3ZLDALvAPe23hj8boeiitZF2Kr1UpfhCvmM7SY73fL25jfK8/7CrDcg8Cy2f5jt/AL"
    "hXn9/z4Ivx4AAAAASUVORK5CYII=")
index.append('contrast_label')
catalog['contrast_label'] = contrast_label
getcontrast_labelData = contrast_label.GetData
getcontrast_labelImage = contrast_label.GetImage
getcontrast_labelBitmap = contrast_label.GetBitmap

#----------------------------------------------------------------------
empty_h = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGDQc3C9aYNLAAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAYElEQVQ4y+2UoQ3AMBAD3cjs"
    "iRfL/ksEmDx7qWVlBWmKqhz3ySY+eu9nZsI2qgozkIQkRASYmRhj4A1VdWebbaxiG212zlOz"
    "ho/Yoi36qYjksoQkmqRlkSQwIu4rWDm2C2yDKKvMrCnrAAAAAElFTkSuQmCC")
index.append('empty_h')
catalog['empty_h'] = empty_h
getempty_hData = empty_h.GetData
getempty_hImage = empty_h.GetImage
getempty_hBitmap = empty_h.GetBitmap

#----------------------------------------------------------------------
empty = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wHAg0yHECo+QIAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAKElEQVQ4y2NgGLaAEZlz9+7d"
    "/6RoVlZWhutnopaLRg0aNWh4GjSMAQAQ/gQYyj3eAQAAAABJRU5ErkJggg==")
index.append('empty')
catalog['empty'] = empty
getemptyData = empty.GetData
getemptyImage = empty.GetImage
getemptyBitmap = empty.GetBitmap

#----------------------------------------------------------------------
ico_contrast = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGDQoFOIzgkoQAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAA0klEQVQ4y7WTbw3DIBTEjxlA"
    "QuekEjYHSEACEiphdfDmoHOABHDApuDtS1leCJCSdJfw5V3vF/5cgZOkGnMN4A7gWswjgCeA"
    "zxG4BZAAcGOl/ZuuXC3snGNrLWut5dy1IKa1i6yUEltrpWdKyNQ5Cpcyxkh/kqBlBMTMPM9z"
    "9hcJCqMgIsp+kM/PvRdgrttK/dqjLmcVMoPeo8EYI2Q2g16joHVdUcuakcv23ne7tB0BEZFs"
    "+Nb6UX0LFEIoi+j3TFOP3jH39Th6lzcAVAHQ7v1PXxCx7khe1G04AAAAAElFTkSuQmCC")
index.append('ico_contrast')
catalog['ico_contrast'] = ico_contrast
getico_contrastData = ico_contrast.GetData
getico_contrastImage = ico_contrast.GetImage
getico_contrastBitmap = ico_contrast.GetBitmap

#----------------------------------------------------------------------
ico_eye_closed_h = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGCwgBFPy7sNEAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAtklEQVQ4y+WUMQrCQBBFX7JN"
    "uhQhYL1NDiDW24gHSaFHMEfYzloIHsErpAmk8AayLOQEYRttLdzCwhRZgyA+mGpmHgwDP+KJ"
    "BFZAyjQccAGs8JI1kDCdxO8PAtgESl7J4oBz3pHGzMSPiZRSubX22HXdXimVB4u01qWUclfX"
    "9VlrXX7lNAEsx5rGmGvTNIeiKBZVVZ36vr+NzUbA9g/fP1XkZvA4Adx9FHxCK4DBVxYQJw5o"
    "AfsAVNgpXsS4t1MAAAAASUVORK5CYII=")
index.append('ico_eye_closed_h')
catalog['ico_eye_closed_h'] = ico_eye_closed_h
getico_eye_closed_hData = ico_eye_closed_h.GetData
getico_eye_closed_hImage = ico_eye_closed_h.GetImage
getico_eye_closed_hBitmap = ico_eye_closed_h.GetBitmap

#----------------------------------------------------------------------
ico_eye_closed = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGCwgBJNpigH0AAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAATUlEQVQ4y+2SsQ3AIBADD8Qk"
    "zlrswUIMkyESr5JUlECTLn/tWbIsGYIfk1bS9gFcwAlUSfcsmzdFXVICGtBXwfzVtLLx1fYz"
    "psUTggkvzZUNSXqxSLQAAAAASUVORK5CYII=")
index.append('ico_eye_closed')
catalog['ico_eye_closed'] = ico_eye_closed
getico_eye_closedData = ico_eye_closed.GetData
getico_eye_closedImage = ico_eye_closed.GetImage
getico_eye_closedBitmap = ico_eye_closed.GetBitmap

#----------------------------------------------------------------------
ico_eye_open_h = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGCwc7OZeRdeAAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAACPUlEQVQ4y6WUP2gacRTHv+ed"
    "kErTQEIHS02DlBZaAmIRxcVCpXTIFHGyIBL8dbsuxqVDTrrU0yxCMwSKWLoJ6VAwHVJoIQRF"
    "lIJe4Up62njUoZhwsZjgv+sQhaPV0pgP/Jb3fb8vv997j0fhDDMAG4AZnA8FQB6ARA9M3ACm"
    "cH6mBvePaAAPJzTRMqeb4DujmGHGKYuLi1e8Xu8dk8l0td/vq8ViUUomk2Kr1eqNyqcAEG3A"
    "brfPchy3vLCwcFeW5a+yLMt6vV5vNptvTk9Pz+7s7LxfXV391O121bFG4XDY4vf7H2ez2Y+R"
    "SOTDwcHBiTbZ6/XeYFl2maZpfSgUerW3t9fQ6gQAiUajr0ul0qHH43k+jBFC1iVJUkVRPCWE"
    "rAMgDMM82dzcfCsIguLz+V4McwGALC0tceVyWXG5XM80AhFF8VRVVXVoptVCodBLQRCOg8Fg"
    "HADRAYDRaLxMURRls9mu/VnESqUyshn5fP6HqqpqvV7/BQA0gHvFYrGhKMo+y7IrFouF2d7e"
    "/tbv99FutyW73W6laZqJxWKJQqHQAACPx2Pief5pJpN5t7GxIfxVbKfTORePx1d6vV4nkUhs"
    "pdPp79pXzM/PX1pbW3vgcDjup1KpNzzPfx7bfoZhqFgs5nK73Y+azeahJEn7nU6nc/2MW9Vq"
    "VeA4biuXyx3+c46GGAwGOhAI3LZarWadTkfVarWf6XT6S6lUOv6vgZwU3WAVXBSFBnAyWAUX"
    "YZcGcDQ4cxOsEwXALgDpN18y7B0739xsAAAAAElFTkSuQmCC")
index.append('ico_eye_open_h')
catalog['ico_eye_open_h'] = ico_eye_open_h
getico_eye_open_hData = ico_eye_open_h.GetData
getico_eye_open_hImage = ico_eye_open_h.GetImage
getico_eye_open_hBitmap = ico_eye_open_h.GetBitmap

#----------------------------------------------------------------------
ico_eye_open = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGCwgACh+vvPMAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAABKUlEQVQ4y+3TMUiWURgF4Kc/"
    "oraWhiaRY1sRhEtLqIO4/bm3BhFBbRVBtJabg0jt7q0RpOHiEkHUFu8fLha0hA2G6OfyGfLZ"
    "X9LsmV7OgXPPPe+9HONfODFMqKrzmMYF7GANy0m2j2RUVSN4hhm8xQecxjWM4CkWk+wONaqq"
    "WTzHAuaT/Ojo45jDGdxI8uWQUVXdxBP0k7xvuSm8wc+WX66qHh7iLmaTrB086VJVbVTVWCfB"
    "ZtM0TVU1VbXZ0fpV9a2qJqHX8ufa+WK3s8FgMGwfn7CL77+NkqzgOl5U1aM2PvTba+3P+2mu"
    "YAWPk3z8U9mjWMIW7id519HP4h7u4FaSl39bfw+320LXsYpfuIwJvMKDJOtHfZCnMIWrOInP"
    "eJ3k6/E//j/sAe2aeTKhCaAWAAAAAElFTkSuQmCC")
index.append('ico_eye_open')
catalog['ico_eye_open'] = ico_eye_open
getico_eye_openData = ico_eye_open.GetData
getico_eye_openImage = ico_eye_open.GetImage
getico_eye_openBitmap = ico_eye_open.GetBitmap

#----------------------------------------------------------------------
ico_pause_h = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGCwgCOgtA7t0AAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAkklEQVQ4y+3UsQmEMBiG4Vdz"
    "hZ2FVdor3OA2ELvUDuIcQnbJCnbu4AqSytbCCCkixGjnPRAIH+SDQPJn7L7ADyi5xgITMAtX"
    "0gAF1xXu/CKANrHEV+UJ1wkpP6HUGNMfe6XUcJb5gkVSyjom8+U85F/06qLgg9RaDzGZLwO6"
    "B/6bFcDqRsEdowAWt6qEcWKBEZg3N2IaTx7xdkoAAAAASUVORK5CYII=")
index.append('ico_pause_h')
catalog['ico_pause_h'] = ico_pause_h
getico_pause_hData = ico_pause_h.GetData
getico_pause_hImage = ico_pause_h.GetImage
getico_pause_hBitmap = ico_pause_h.GetBitmap

#----------------------------------------------------------------------
ico_pause = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGCwgDFiCDs38AAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAOklEQVQ4y2NgGAWEACM2wTNn"
    "zuyHsU1MTBxxiSEDFhwWOBApBgdM1PLaqEEj2iCsCZKJicmBGLERAgBzMwkmkuGaFgAAAABJ"
    "RU5ErkJggg==")
index.append('ico_pause')
catalog['ico_pause'] = ico_pause
getico_pauseData = ico_pause.GetData
getico_pauseImage = ico_pause.GetImage
getico_pauseBitmap = ico_pause.GetBitmap

#----------------------------------------------------------------------
ico_play_h = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGBhALEOFmtlcAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAABEklEQVQ4y6WToW6DUBiFT2Es"
    "2QKKBgEO0RfoNTNLSAV+kCnE1CQhqYEHoAmOJ+AlaHAlVyEAMUlmZoaca7YsTMy0DenSjkuP"
    "PP89X+5/c88EwAwAASCCTVsANQ/AHBEGgGsAU25keC+RO3YIIXIYhgtN026GEHgA877h+/7C"
    "MIwH27bvdV3/yfP87RyAOzUQBOHWNM1HSukqCII7ZsBhSVGULct6opSuHMeZMQP6IM/zlmma"
    "LgkhMjNgL0mSZEVRDg98NTTYdd1nVVUb13XXfX8QoCiKNIqiTdu2X8ezs4CmaYo4jtd1XX+c"
    "OvMHUJblq6qqL0mSpFmWvf93uwmA5wu+Mrhdq8ZqywP4BjDdtYu5zr+ZH0lj58fEmAAAAABJ"
    "RU5ErkJggg==")
index.append('ico_play_h')
catalog['ico_play_h'] = ico_play_h
getico_play_hData = ico_play_h.GetData
getico_play_hImage = ico_play_h.GetImage
getico_play_hBitmap = ico_play_h.GetBitmap

#----------------------------------------------------------------------
ico_play = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGBhALG3a0b98AAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAApklEQVQ4y92RwQ2CQBBF/2wo"
    "gA6wBpa7LdiBdmAL2MGWQAl2IAX8TGIFaAfawA4XMRvUINz03eZn5s0kA/w8Mg5UtYgxbgA0"
    "VVXdpwRuHJjZDkAAcCG5ny1IyAEEkh3J7RLBwApAQ7JT1fUSwVMUY2xJnlS1WCJIL8qHIpsx"
    "eBOR4L0/pOFXAhGpzSx471/eOiVonHN1WZbXTw3Zm22tmR0fg2f8Pz2rRzf1tieeSAAAAABJ"
    "RU5ErkJggg==")
index.append('ico_play')
catalog['ico_play'] = ico_play
getico_playData = ico_play.GetData
getico_playImage = ico_play.GetImage
getico_playBitmap = ico_play.GetBitmap

#----------------------------------------------------------------------
ico_rem_str_h = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AAAAAAAA+UO7fwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGFAsyICNY2MQAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAi0lEQVQ4y92UsQmAMBBFX4yF"
    "nUU2cAc3EGun0JncwiHs3EFwgpBGCwstTCEiojGF+OCag//gc3CCjQRIgZhnGKADemklGRDx"
    "nMjmtQRyR8keFTjUOSMO8MT3ROFxsRRFfScomqa6FA3j+LFqep6dRAIo/3l+ryLjwWMkMNlX"
    "8IZWAtqOcngnBmiBfgUivxeWIVaLjgAAAABJRU5ErkJggg==")
index.append('ico_rem_str_h')
catalog['ico_rem_str_h'] = ico_rem_str_h
getico_rem_str_hData = ico_rem_str_h.GetData
getico_rem_str_hImage = ico_rem_str_h.GetImage
getico_rem_str_hBitmap = ico_rem_str_h.GetBitmap

#----------------------------------------------------------------------
ico_rem_str = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AAAAAAAA+UO7fwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGFAsyN6CLXQMAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAANUlEQVQ4y2NgGAUjGDCiC9y4"
    "ceM/MRo1NDRQ9LKgK3j16hVZLmKiltcwXPTy5cvRCB8FpAIA/GAJhRp0vwYAAAAASUVORK5C"
    "YII=")
index.append('ico_rem_str')
catalog['ico_rem_str'] = ico_rem_str
getico_rem_strData = ico_rem_str.GetData
getico_rem_strImage = ico_rem_str.GetImage
getico_rem_strBitmap = ico_rem_str.GetBitmap

#----------------------------------------------------------------------
stream_add_h = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAHYAAAAdCAYAAAB/lJiIAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AAAAAAAA+UO7fwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wHAg4jGWFdkMQAAARc"
    "SURBVGje7Zt/SFtXFMe/eVYHErP4c3Vjkxr/2B9zEpnZ/EXVWSGLLtStImgNNKAGNf7KH0H0"
    "LxEdQWVZwnBjIRZxQShBqX/UrRmNbiiaja2CwsyKK3ZRY+aSDDQxj/1hMl4zjc/abfp4H7iQ"
    "3HPf5Z5zOOfe87iPg38SDSANQAaAywBiwHIe8QFwAFgDsA7ATxVywgZnAChhbXYhsQSdDACI"
    "ogjeApDH2ufCciUYqE+ojs1gncoIUgH8AcBFBPdUNv0yhxIA0UTwoMTCLNKIYBpmYRYZRLCk"
    "YWEWlwm2TmUkMQRrA2Zyidaoxxj5+/eraGDNxhTHbrCGYqZjnyNKpfKN1tbWFr1erx8aGvop"
    "1G+320cAIBAIHHg8HqfNZptvbm6+5/P5SDpyKvX19a/L5fIP4uPjU71er2tycvJuXV2dPHyc"
    "QCBooM5NkmTA7XY7TSbTHY1G8yNVdtRzkXQxGAyf9/X1LYX6dDrdNbFY/GHo2X8bImL6DTU6"
    "/TSRSqVFa2trP5SXlxcdZbC8vLz24eHh0aysrGytVnvtNPIQLS0tt2ZmZu6LRKL2jo4OnUgk"
    "yhQIBA0ho1J/U+fOzMxsHh0dnZDJZDfDZdRGRxexWFxCEAQHAGJjY6NEItE7/2UAERHT78YR"
    "afi4fhrk5+cn8Xi8BKlU+llcXFx8YWFhUvgYp9PpGxsb+6W/v/92Tk5O/mnlAOD3+/eSk5Nf"
    "rKioeG15eXlXIpF8QWd9JHkY/IFA4OCsumxsbPza2dn5JgB0dXW9vbq6+vB8OPYxpdHpp4FC"
    "obhqNpun9/b2SLPZfFehUFw9buzc3Nwml8tNeBZ5W1vbJ4mJiQlNTU1Vs7OzH/X09OSctDa7"
    "3T6ysrLyaW1t7XW1Wv1xuIza6Oii1+vvV1ZWvkcQBKesrOxdrVb74HzssTcop995Stq98Wyn"
    "Yj6fHy0UCvNzc3PL5PLD7W5/f/9PPp8/tbu76w8fX1BQ8JLX63UdN18kudVq3bZarV8CgEQi"
    "eXlgYKC9t7d3MdL6BAJBQ0pKygs6ne56enp6PIDfwvfU0+hitVq3PR7P7sTERPXOzo5jaWnp"
    "9/MRsc8ZlUqVs7m5+Yi6VzkcjkcqleqpaEpKSoqpqalJV6vVNxcXF78Nn+ckOQBMT0/fKi4u"
    "TuHxeJeys7Nf4XA4HDpr3Nra2m9sbLwjk8kq09LSYs+qy/j4+NdCobDIZDJZzmsde2ZKS0uL"
    "TCbTFLVvamrqm+rq6oru7u7vQimPJMkDt9vttNls80ql8qvwlBhJHmJhYeHh4OBgM5fLTXS7"
    "3VsGg+E23XW6XC6/xWJ5oNFo3q+qqjIddTLe3t5eP0kXADAajT8bjcb/pe7nAKhnqz7mwb5S"
    "ZLBjfawZGIePwOFNNxZm4SBAudnGwhjWCBzeSWVhFutRAEgc3my7wtqDEVgAOEPXT13B0ieV"
    "tcuF5nsAy8DTF8afsJF74SN1OfTnqFdt7Lc7F6SkQYRvd/4C+iYbcLsfcC4AAAAASUVORK5C"
    "YII=")
index.append('stream_add_h')
catalog['stream_add_h'] = stream_add_h
getstream_add_hData = stream_add_h.GetData
getstream_add_hImage = stream_add_h.GetImage
getstream_add_hBitmap = stream_add_h.GetBitmap

#----------------------------------------------------------------------
stream_add = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAHYAAAAdCAYAAAB/lJiIAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AAAAAAAA+UO7fwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wHAg4hB6lkzyUAAAJh"
    "SURBVGje7ZjLaxNRFIe/SAWpf4FQFf2BBCkKrl0JgnbRXWihuPCx8YkgPhBEaxdaLEWxdGuh"
    "FaSCUKrduIugUMSlRPEoFC0kCxHEd0vc3CnDMImTBCWW88GFmXPm3plzTu7vHgKO4ziO4ziO"
    "4ziO4ziO8zfINTuxVCpVo+t8Pp/zVLYXHc1OrFQqnr3VWNhmMbP9wBzQK2k2Zo8U4AfwDpgE"
    "hiUtZ/En3rEHuAFsBxaAQeBu8jlJucTav4C3wHlJMwlf2rx6sfRJmo7ZzgAj0dy2KmxcfuM7"
    "tkFZPg48AI4Bs8mEmVknsBMYA5aB4az+GFPABWAa6AIG40VMS25YuwPYC0wAM8lCNhILcMrM"
    "7kuqmtla4MC/3EBrGpXfaGSxp+ykLcAmoA/oMrOtKQn+KukZcBg42Kg/8BnYAOwCFiUNZAwx"
    "rgqtxvIC6A3XA2Fnt2dhy+XyyshiT+EoMCRpCbga7mvxOiSuGX8PsBG4CXwws/4MhaoCS8A1"
    "YF/SFx8ZY7kFXDSzHHAaGG/bM7ZQKKxIUrFYrKbZ6yRuHXAIOGtmkfmjmV2S9D1lyrZwPtai"
    "pl+SASfCe7uBx8C9et8XpHg9cD3I98taUpwlFklmZovhyHgl6X3s2VXVPPUD85J6YgmaC/aJ"
    "mK0T2AHcBu6k/EDq+sMzU6FhWgC6syqTpC9mdg54ambzkj61EgswChSB3f9NV5xBdtMajcsJ"
    "2xhwJUpGkLmfoTOdBEZS5LKmP8Yj4CGwGXgDHMn6kZK+mdk4MAScrNEZP/9TLGGtJ638V+A4"
    "juM4juM4juM4juM47cdvmF9CbQJGOBoAAAAASUVORK5CYII=")
index.append('stream_add')
catalog['stream_add'] = stream_add
getstream_addData = stream_add.GetData
getstream_addImage = stream_add.GetImage
getstream_addBitmap = stream_add.GetBitmap

