#----------------------------------------------------------------------
# This file was generated by /usr/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

catalog = {}
index = []

arr_down = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGBA0ZOvze9/oAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAOUlEQVQ4y2NgGAXDCKQxMDD8"
    "JwOnYTOEGIChGd0QRnI0E+MSgprRDWEmRzM2l5CsGd2QNEqjmHYAABHkHedSYhkyAAAAAElF"
    "TkSuQmCC")
index.append('arr_down')
catalog['arr_down'] = arr_down
getarr_downData = arr_down.GetData
getarr_downImage = arr_down.GetImage
getarr_downBitmap = arr_down.GetBitmap

#----------------------------------------------------------------------
arr_right = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGBA0aAv/xHKcAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAQUlEQVQ4y63TuQ0AIBADQdMs"
    "/XdgcgIQGlzA6s5PctYMqgqpQqqXVN+perIDxiukmk412q8eUArUA24ibYHXeNUCucUd5GAZ"
    "baUAAAAASUVORK5CYII=")
index.append('arr_right')
catalog['arr_right'] = arr_right
getarr_rightData = arr_right.GetData
getarr_rightImage = arr_right.GetImage
getarr_rightBitmap = arr_right.GetBitmap

#----------------------------------------------------------------------
arr_s_down = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGBA0dBrfdTnkAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAMklEQVQ4y2NgGAXDDKQxMDD8"
    "JwGn4TMEH8CpmRhDCGrGZwjRmrEZQrJmdEPSKI2dQQwA5FgZGxaMtPkAAAAASUVORK5CYII=")
index.append('arr_s_down')
catalog['arr_s_down'] = arr_s_down
getarr_s_downData = arr_s_down.GetData
getarr_s_downImage = arr_s_down.GetImage
getarr_s_downBitmap = arr_s_down.GetBitmap

#----------------------------------------------------------------------
arr_s_right = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGBA0dOHa8U9IAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAN0lEQVQ4y2NgGOwgjVID/lNq"
    "yH9KDflPqUv+U+qd/5SGyX9KA5aqLqAoDCiKBYrTQdqA5gWCAABDZRkbE+EX3wAAAABJRU5E"
    "rkJggg==")
index.append('arr_s_right')
catalog['arr_s_right'] = arr_s_right
getarr_s_rightData = arr_s_right.GetData
getarr_s_rightImage = arr_s_right.GetImage
getarr_s_rightBitmap = arr_s_right.GetBitmap

#----------------------------------------------------------------------
contrast_label = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADIAAAASCAYAAAAZk42HAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGDgkDA3tCzZEAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAACLUlEQVRIx+2WP2gUURDGfxeC"
    "YHWIoAiSRBGsxMr6rks13h2klSMg/teNCrbL2dgEIaCFjdlYaCBFFkasFSy0kFywi8E7NNgI"
    "nilsAvJsZsNz7/a8NQQu4gePZWbezHvfm9l5D/4RFDL0RaAKTKT0bSAGNvcCuQDoAC5jdGzO"
    "UCPstfkwDF0QBK5YLPr6cFhJ1LOykKDT6bggCHxbfdhIjPcpJZdGvV737eP9AovIpIg4EZnM"
    "syER+ZJn/oh9Z/I4RVFEqVRiQN8AeATcyHm4R/6ma7V6dKhtOOe6dHEcU6vVkk52LONUTwKv"
    "gDFgFaio6ppnd6pa6CWLyG+LqmpBREaBu8BlUz8EQlX9OWqKiby1WK1WGcD3FvBMVbdE5IFl"
    "5+qga/gkDbeBM8Apk58AN4HZkd366UTkIHAOiJKKBM6KyIEdhJ0GAlXdUNUNK9fz/j/yPW/E"
    "drvNH3wvAGuqumqn+wN4ClzcAZEx4KMnr5tum8jLvBGjKDnobl+r5SvAaetYzmr+DnDN7ACb"
    "IrI/Y4ktEdmX0n0GjnvyCeATQBIwtifJQGg2mzQaDTzfNKaAw8AhVf2aIrlk9kXgNVAzXZrQ"
    "OlARkefAUVX9YOU5JyLTNmcOeOxnZGHQrMRxTLlc9rOx0GPaDPAiTcJw32vZ14FL9nZrA29T"
    "jeIe8C3ZLDALvAPe23hj8boeiitZF2Kr1UpfhCvmM7SY73fL25jfK8/7CrDcg8Cy2f5jt/AL"
    "hXn9/z4Ivx4AAAAASUVORK5CYII=")
index.append('contrast_label')
catalog['contrast_label'] = contrast_label
getcontrast_labelData = contrast_label.GetData
getcontrast_labelImage = contrast_label.GetImage
getcontrast_labelBitmap = contrast_label.GetBitmap

#----------------------------------------------------------------------
empty_h = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGDQc3C9aYNLAAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAYElEQVQ4y+2UoQ3AMBAD3cjs"
    "iRfL/ksEmDx7qWVlBWmKqhz3ySY+eu9nZsI2qgozkIQkRASYmRhj4A1VdWebbaxiG212zlOz"
    "ho/Yoi36qYjksoQkmqRlkSQwIu4rWDm2C2yDKKvMrCnrAAAAAElFTkSuQmCC")
index.append('empty_h')
catalog['empty_h'] = empty_h
getempty_hData = empty_h.GetData
getempty_hImage = empty_h.GetImage
getempty_hBitmap = empty_h.GetBitmap

#----------------------------------------------------------------------
empty = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGDQkJGBl9QxkAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAKElEQVQ4y2NgGLaAEZlz6NCh"
    "/6RotrOzg+tnopaLRg0aNWh4GjSMAQABzgQYFogwjQAAAABJRU5ErkJggg==")
index.append('empty')
catalog['empty'] = empty
getemptyData = empty.GetData
getemptyImage = empty.GetImage
getemptyBitmap = empty.GetBitmap

#----------------------------------------------------------------------
ico_contrast = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGDQoFOIzgkoQAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAA0klEQVQ4y7WTbw3DIBTEjxlA"
    "QuekEjYHSEACEiphdfDmoHOABHDApuDtS1leCJCSdJfw5V3vF/5cgZOkGnMN4A7gWswjgCeA"
    "zxG4BZAAcGOl/ZuuXC3snGNrLWut5dy1IKa1i6yUEltrpWdKyNQ5Cpcyxkh/kqBlBMTMPM9z"
    "9hcJCqMgIsp+kM/PvRdgrttK/dqjLmcVMoPeo8EYI2Q2g16joHVdUcuakcv23ne7tB0BEZFs"
    "+Nb6UX0LFEIoi+j3TFOP3jH39Th6lzcAVAHQ7v1PXxCx7khe1G04AAAAAElFTkSuQmCC")
index.append('ico_contrast')
catalog['ico_contrast'] = ico_contrast
getico_contrastData = ico_contrast.GetData
getico_contrastImage = ico_contrast.GetImage
getico_contrastBitmap = ico_contrast.GetBitmap

#----------------------------------------------------------------------
ico_eye_closed_h = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGCwgBFPy7sNEAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAtklEQVQ4y+WUMQrCQBBFX7JN"
    "uhQhYL1NDiDW24gHSaFHMEfYzloIHsErpAmk8AayLOQEYRttLdzCwhRZgyA+mGpmHgwDP+KJ"
    "BFZAyjQccAGs8JI1kDCdxO8PAtgESl7J4oBz3pHGzMSPiZRSubX22HXdXimVB4u01qWUclfX"
    "9VlrXX7lNAEsx5rGmGvTNIeiKBZVVZ36vr+NzUbA9g/fP1XkZvA4Adx9FHxCK4DBVxYQJw5o"
    "AfsAVNgpXsS4t1MAAAAASUVORK5CYII=")
index.append('ico_eye_closed_h')
catalog['ico_eye_closed_h'] = ico_eye_closed_h
getico_eye_closed_hData = ico_eye_closed_h.GetData
getico_eye_closed_hImage = ico_eye_closed_h.GetImage
getico_eye_closed_hBitmap = ico_eye_closed_h.GetBitmap

#----------------------------------------------------------------------
ico_eye_closed = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGCwgBJNpigH0AAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAATUlEQVQ4y+2SsQ3AIBADD8Qk"
    "zlrswUIMkyESr5JUlECTLn/tWbIsGYIfk1bS9gFcwAlUSfcsmzdFXVICGtBXwfzVtLLx1fYz"
    "psUTggkvzZUNSXqxSLQAAAAASUVORK5CYII=")
index.append('ico_eye_closed')
catalog['ico_eye_closed'] = ico_eye_closed
getico_eye_closedData = ico_eye_closed.GetData
getico_eye_closedImage = ico_eye_closed.GetImage
getico_eye_closedBitmap = ico_eye_closed.GetBitmap

#----------------------------------------------------------------------
ico_eye_open_h = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGCwc7OZeRdeAAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAACPUlEQVQ4y6WUP2gacRTHv+ed"
    "kErTQEIHS02DlBZaAmIRxcVCpXTIFHGyIBL8dbsuxqVDTrrU0yxCMwSKWLoJ6VAwHVJoIQRF"
    "lIJe4Up62njUoZhwsZjgv+sQhaPV0pgP/Jb3fb8vv997j0fhDDMAG4AZnA8FQB6ARA9M3ACm"
    "cH6mBvePaAAPJzTRMqeb4DujmGHGKYuLi1e8Xu8dk8l0td/vq8ViUUomk2Kr1eqNyqcAEG3A"
    "brfPchy3vLCwcFeW5a+yLMt6vV5vNptvTk9Pz+7s7LxfXV391O121bFG4XDY4vf7H2ez2Y+R"
    "SOTDwcHBiTbZ6/XeYFl2maZpfSgUerW3t9fQ6gQAiUajr0ul0qHH43k+jBFC1iVJUkVRPCWE"
    "rAMgDMM82dzcfCsIguLz+V4McwGALC0tceVyWXG5XM80AhFF8VRVVXVoptVCodBLQRCOg8Fg"
    "HADRAYDRaLxMURRls9mu/VnESqUyshn5fP6HqqpqvV7/BQA0gHvFYrGhKMo+y7IrFouF2d7e"
    "/tbv99FutyW73W6laZqJxWKJQqHQAACPx2Pief5pJpN5t7GxIfxVbKfTORePx1d6vV4nkUhs"
    "pdPp79pXzM/PX1pbW3vgcDjup1KpNzzPfx7bfoZhqFgs5nK73Y+azeahJEn7nU6nc/2MW9Vq"
    "VeA4biuXyx3+c46GGAwGOhAI3LZarWadTkfVarWf6XT6S6lUOv6vgZwU3WAVXBSFBnAyWAUX"
    "YZcGcDQ4cxOsEwXALgDpN18y7B0739xsAAAAAElFTkSuQmCC")
index.append('ico_eye_open_h')
catalog['ico_eye_open_h'] = ico_eye_open_h
getico_eye_open_hData = ico_eye_open_h.GetData
getico_eye_open_hImage = ico_eye_open_h.GetImage
getico_eye_open_hBitmap = ico_eye_open_h.GetBitmap

#----------------------------------------------------------------------
ico_eye_open = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGCwgACh+vvPMAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAABKUlEQVQ4y+3TMUiWURgF4Kc/"
    "oraWhiaRY1sRhEtLqIO4/bm3BhFBbRVBtJabg0jt7q0RpOHiEkHUFu8fLha0hA2G6OfyGfLZ"
    "X9LsmV7OgXPPPe+9HONfODFMqKrzmMYF7GANy0m2j2RUVSN4hhm8xQecxjWM4CkWk+wONaqq"
    "WTzHAuaT/Ojo45jDGdxI8uWQUVXdxBP0k7xvuSm8wc+WX66qHh7iLmaTrB086VJVbVTVWCfB"
    "ZtM0TVU1VbXZ0fpV9a2qJqHX8ufa+WK3s8FgMGwfn7CL77+NkqzgOl5U1aM2PvTba+3P+2mu"
    "YAWPk3z8U9mjWMIW7id519HP4h7u4FaSl39bfw+320LXsYpfuIwJvMKDJOtHfZCnMIWrOInP"
    "eJ3k6/E//j/sAe2aeTKhCaAWAAAAAElFTkSuQmCC")
index.append('ico_eye_open')
catalog['ico_eye_open'] = ico_eye_open
getico_eye_openData = ico_eye_open.GetData
getico_eye_openImage = ico_eye_open.GetImage
getico_eye_openBitmap = ico_eye_open.GetBitmap

#----------------------------------------------------------------------
ico_pause_h = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGCwgCOgtA7t0AAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAkklEQVQ4y+3UsQmEMBiG4Vdz"
    "hZ2FVdor3OA2ELvUDuIcQnbJCnbu4AqSytbCCCkixGjnPRAIH+SDQPJn7L7ADyi5xgITMAtX"
    "0gAF1xXu/CKANrHEV+UJ1wkpP6HUGNMfe6XUcJb5gkVSyjom8+U85F/06qLgg9RaDzGZLwO6"
    "B/6bFcDqRsEdowAWt6qEcWKBEZg3N2IaTx7xdkoAAAAASUVORK5CYII=")
index.append('ico_pause_h')
catalog['ico_pause_h'] = ico_pause_h
getico_pause_hData = ico_pause_h.GetData
getico_pause_hImage = ico_pause_h.GetImage
getico_pause_hBitmap = ico_pause_h.GetBitmap

#----------------------------------------------------------------------
ico_pause = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGCwgDFiCDs38AAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAOklEQVQ4y2NgGAWEACM2wTNn"
    "zuyHsU1MTBxxiSEDFhwWOBApBgdM1PLaqEEj2iCsCZKJicmBGLERAgBzMwkmkuGaFgAAAABJ"
    "RU5ErkJggg==")
index.append('ico_pause')
catalog['ico_pause'] = ico_pause
getico_pauseData = ico_pause.GetData
getico_pauseImage = ico_pause.GetImage
getico_pauseBitmap = ico_pause.GetBitmap

#----------------------------------------------------------------------
ico_play_h = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGBhALEOFmtlcAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAABEklEQVQ4y6WToW6DUBiFT2Es"
    "2QKKBgEO0RfoNTNLSAV+kCnE1CQhqYEHoAmOJ+AlaHAlVyEAMUlmZoaca7YsTMy0DenSjkuP"
    "PP89X+5/c88EwAwAASCCTVsANQ/AHBEGgGsAU25keC+RO3YIIXIYhgtN026GEHgA877h+/7C"
    "MIwH27bvdV3/yfP87RyAOzUQBOHWNM1HSukqCII7ZsBhSVGULct6opSuHMeZMQP6IM/zlmma"
    "LgkhMjNgL0mSZEVRDg98NTTYdd1nVVUb13XXfX8QoCiKNIqiTdu2X8ezs4CmaYo4jtd1XX+c"
    "OvMHUJblq6qqL0mSpFmWvf93uwmA5wu+Mrhdq8ZqywP4BjDdtYu5zr+ZH0lj58fEmAAAAABJ"
    "RU5ErkJggg==")
index.append('ico_play_h')
catalog['ico_play_h'] = ico_play_h
getico_play_hData = ico_play_h.GetData
getico_play_hImage = ico_play_h.GetImage
getico_play_hBitmap = ico_play_h.GetBitmap

#----------------------------------------------------------------------
ico_play = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGBhALG3a0b98AAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAApklEQVQ4y92RwQ2CQBBF/2wo"
    "gA6wBpa7LdiBdmAL2MGWQAl2IAX8TGIFaAfawA4XMRvUINz03eZn5s0kA/w8Mg5UtYgxbgA0"
    "VVXdpwRuHJjZDkAAcCG5ny1IyAEEkh3J7RLBwApAQ7JT1fUSwVMUY2xJnlS1WCJIL8qHIpsx"
    "eBOR4L0/pOFXAhGpzSx471/eOiVonHN1WZbXTw3Zm22tmR0fg2f8Pz2rRzf1tieeSAAAAABJ"
    "RU5ErkJggg==")
index.append('ico_play')
catalog['ico_play'] = ico_play
getico_playData = ico_play.GetData
getico_playImage = ico_play.GetImage
getico_playBitmap = ico_play.GetBitmap

#----------------------------------------------------------------------
ico_rem_str_h = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AAAAAAAA+UO7fwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGFAsyICNY2MQAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAAi0lEQVQ4y92UsQmAMBBFX4yF"
    "nUU2cAc3EGun0JncwiHs3EFwgpBGCwstTCEiojGF+OCag//gc3CCjQRIgZhnGKADemklGRDx"
    "nMjmtQRyR8keFTjUOSMO8MT3ROFxsRRFfScomqa6FA3j+LFqep6dRAIo/3l+ryLjwWMkMNlX"
    "8IZWAtqOcngnBmiBfgUivxeWIVaLjgAAAABJRU5ErkJggg==")
index.append('ico_rem_str_h')
catalog['ico_rem_str_h'] = ico_rem_str_h
getico_rem_str_hData = ico_rem_str_h.GetData
getico_rem_str_hImage = ico_rem_str_h.GetImage
getico_rem_str_hBitmap = ico_rem_str_h.GetBitmap

#----------------------------------------------------------------------
ico_rem_str = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AAAAAAAA+UO7fwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGFAsyN6CLXQMAAAAZ"
    "dEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAANUlEQVQ4y2NgGAUjGDCiC9y4"
    "ceM/MRo1NDRQ9LKgK3j16hVZLmKiltcwXPTy5cvRCB8FpAIA/GAJhRp0vwYAAAAASUVORK5C"
    "YII=")
index.append('ico_rem_str')
catalog['ico_rem_str'] = ico_rem_str
getico_rem_strData = ico_rem_str.GetData
getico_rem_strImage = ico_rem_str.GetImage
getico_rem_strBitmap = ico_rem_str.GetBitmap

#----------------------------------------------------------------------
stream_add_h = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAHYAAAAfCAYAAAAyXDmDAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AMIAwgDCjdfhdgAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGFAwYERiiAlMAAAYG"
    "SURBVGje7ZtrSFtnGMf/J1dzorY2q9oaN+YHM8HOzUhltTbgrVEGpt1k1WmgINN2bWHi2JpO"
    "qIxhaHCtKKXCVpgfCu0sWjWdS4p0UG9p7AotTdcZmWSh8RJNissac9uHJC64GGOgzsj5wQs5"
    "7/Oe5DzPP+/lnOc9BMKDBmAXgBRf4QFg++opXh1uAHYAZgBGX1nw1YeEWMfOApABIJeK8ZZi"
    "HIAOwHIkwqYBKKJiuKW5A2AqmIG+xrB7CMB+Km5bnjQAsQAMADyhhKUBEPtOoIgOXgOQCEAf"
    "KO5qYQ9RokYl8QC4AKaDCZtGDb9R33MXfWXldoVFLZS2BUU+LVeEzaBism3I8AtLo+5TtxW5"
    "AGgMeJ8obRwDOlc+p6KOiueWYhcD3keEG8cY2S+mp6fHd3Z2tvT29v7Q1tamAYDMzMydbW1t"
    "zW6320UQBObn5//o7u6+3d3dPRmOfTW1tbVvSySSo2w2O97lci0PDQ3183i8ndnZ2YUEQRAs"
    "Fotjt9ttAHD37t3ewsLCD9xut8vpdC7PzMzo5XL5DZ1OZxUKhbyLFy9+428LAPfv31fLZLKf"
    "1vIFAK5du/ap2WyeO3369I3A67p+/fpnBoNhqrGx8dYrFjYlcmEjpLa29pDFYjGKRKICfzDY"
    "bDYdgKe4uLiBJEmGVCrdV1dXV+9yuS739PRMrWcP/H6SJBlVVVW1ra2trUqlcjo1NZWMi4tj"
    "PXnyxAJAKRQKeRcuXGgqLi5uAAChUMgrKCg4WlRU1MBms2lyubz83LlzH1dXV18GAIfD8dLf"
    "NhxfACA2NnZXcnJyRkZGxs86nc4KAFVVVW/t2bNHYLFY5jYhzCk0eB/ohz/8+ks49atgMpm0"
    "rKysgwqF4nsul7uzpKSEv7qNzWZzXrly5dfh4eHBioqKso3aY2NjGTQajTk3N/cXABgMBptP"
    "1HWx2+3ugYEBze7du99Yr20oXzgcTsLk5KTmxIkTJf46iURS9vTp02Eulxu/CcLyaPBmacIf"
    "fo1BhuG16lchlUozX7x4MTcyMjLz+PHjMYlEkr9W2/Hx8Wc8Hi91o/bZ2dmXo6Oj/S0tLV91"
    "dHR8dODAgaRw3SNJklFWVpazuLhoDBAwRqVSKfwlKysrIZQvHA6Hzmazyfb29n6BQLA/OTk5"
    "prS09HUOhxM/ODg4QpJk3CYIy2bAmxbihNljEbBgCl4fApFI9N6DBw80ADAwMKCRyWSNJEn+"
    "GOKU9bJPQe1nz569nZOTo6msrMxrbm7+QqVSdSsUipEQvS9GpVIpmEwmabFYjE1NTZf9NofD"
    "8bKkpOTzcH1JTExkO51O56NHjxb1ev3EyZMnD/L5/Nfv3bunNplMS0wmk7MJwtoZ8Ob6+GE1"
    "rwhY/Y4FDLsV66+KU1JSSD6fvy8pKelNkUhU6g9oTU1Nplar/c9fIzc3N91sNq/5l1nPrtVq"
    "57Va7S2pVPr7sWPHKkMJ6xfvyJEjafX19Z9YrdblSH0ZGRmZ9ng8TgDo6uoaOn/+fANBEDhz"
    "5kyXQCDYQafTmZsgrJkW+fp2Y1RXV79rMpl0hw8f/lIsFsvEYrFseHi4Ly8vL3f1cFhXV/dO"
    "Xl6e+ObNm7eDDZfr2cvLy9MIgiAAYO/evbzl5eW/w7nGnp6eKb1e/7CpqelopL6wWKyVzQdj"
    "Y2Ozz58/fzYxMfHL0tKSEwDodDpjE8JtZEQsrGFjzbOzs/drNJrRwLq+vr4JuVz+PpfL7QMA"
    "tVrd6na7HWaz2Xjp0qV2pVI57VvUuELZAxEIBDtqamo+PHXqVKLH44HVajV1dHR0hXudcrm8"
    "/+rVq1/n5+ffsdlsDiaTGaNWq7/12xcWFgwAsJYvCQkJysD648ePXw08ptFom9FjjYTvyVMt"
    "dU+/rfiODm8Ozxn2PEux1RkHYPLPBzoqHtsGHfBvPtYFbx6PSrJHN3cAzAcKC5+wsfAmbCmi"
    "j98APPQf0IOsdRPh3WpBET38CWAIIfY8eeDdFMWlem5U9dQhrNpEHmz7qQfeTVHUnBsdc+pD"
    "rNp6ClBvAkTzLU3EbwIEQr278/8Q8bs7FBQU0cQ/LPqkneRfGTgAAAAASUVORK5CYII=")
index.append('stream_add_h')
catalog['stream_add_h'] = stream_add_h
getstream_add_hData = stream_add_h.GetData
getstream_add_hImage = stream_add_h.GetImage
getstream_add_hBitmap = stream_add_h.GetBitmap

#----------------------------------------------------------------------
stream_add = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAHYAAAAfCAYAAAAyXDmDAAAAAXNSR0IArs4c6QAAAAZiS0dE"
    "AAAAAAAA+UO7fwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9wGFAwJLBMTbVIAAAL2"
    "SURBVGje7ZZLaFRnFMd/scZkNYQ2mIRgKy5CdsGASDf/QjalgSxKCX0FsTFVV7UBF7ZNiPRB"
    "UKqQRZEuROgii7a0hW6yqAUP0iAGWxRl0FQplppMQ0sjLdFIx0XPhMswj5uR2FmcH3zce885"
    "33e/8/geEARBEARBEARBEARBEAQbQUOtHbPZbL7w3t3d3RChrC8219oxl8vV1M/M2oBfgGFJ"
    "0y7rBK4Bq15sF4EPJZ1Poy/xjwHgGLAV+Ac4CnQCh4BNQAvwh5uPAcd97L+BWeBtSXfMbDtw"
    "M2ELcELSZDlfXP4tMC9ptGhe3wGzksY3OrGb/odiOghcAd5KyBqBvKRWoAP4FPjKzJ5NqU8G"
    "bwswDexx+x5gRtIH/t0LLEtq9e8Z4F9JTwE7PJGnEkOu2XqbrOILwNPAATPrSMyrD+jzYqOu"
    "EpvNZvOFlkZeIuhPACPA60CnmfUU20i6L+lrYBJ4b716oAloLqwySX9K+i2Nf5IeeFHsSrHz"
    "VPKl08c5nJCNAaeBtrpLbC6XW2tp5CV4AfhZ0nXgM+DNCrbngJ3r1Uu661vvJTObMrOudRwT"
    "W4CXfRUWyJjZQqJtq+SLmTUCT/ocXjOzjJn1ekLP1GViFxcX11oaeQn2eiXjz1c8mLVe7hrK"
    "rLyPPOl3gR/M7I0q42TMbAFYBp4H9hVtxe2JdruKLxlgRdKvwJe+qkeBk8CS6+vr8jQ4ONiQ"
    "qO58KXmF1dAC9AO7zezdQkBd9lOJLs8BP1YYsqJe0i1gzMwM+MRXSzmWJbX7mf25X7hq9WUO"
    "uO+yKeB7L8ARvx801/WtuAZeAs5KGkgE6AgwlEysV30/8A7wYpntspq+F7ggKQ88A/yV8oyd"
    "NbNv/Ea9/1F9kTTvhXVV0r3/Xmmq68Sm2HaLedXPoiRfABPAuAfnd2AFuAz0S5pzu9Uq+iQd"
    "wMdAl+8qWWB4HfOcAG6Y2Un/V8bMlhL6QuLK+fJ+UbEMFdk1EwRBEARBEARBEARBEARBEASP"
    "gYch/m3UgJ6X0AAAAABJRU5ErkJggg==")
index.append('stream_add')
catalog['stream_add'] = stream_add
getstream_addData = stream_add.GetData
getstream_addImage = stream_add.GetImage
getstream_addBitmap = stream_add.GetBitmap

#----------------------------------------------------------------------
stream_add_sel = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAHYAAAAfCAYAAAAyXDmDAAAFoUlEQVRoge2aP2zTWhTGv+MW"
    "oWQgSDcDSI3olIzYRAz28lq5q0snKrZ2YejCe+ryGJCehARLKnViYGmWDmHqw3NEWRy9oY0Z"
    "kBov4cmRyBBHZbEXmvsGYj+7+R9aQpF/U+JzfHzO/e69vrYvYUzy+Xzq7OxsQxCERc65GDKJ"
    "RHRz3Dgxo+GcmwBOAYCITgGYnPPDarX6ftwYNMpBFMUHRPQ7ES1NnWnMhcA5PyWiXc55sVqt"
    "/jvMd6CwkiTdBVAkInGQT8xs6ApcPD4+/mOQT19h7927twdg47ISi7kYOOenAJaq1eqH8zbh"
    "/AFRFJ8gFvVK0F3bHOTz+VSPLfxHFMUngiDs/rDMYi6E7sgVw/fdQFhRFB8IgnAwk8xivhvO"
    "uSkIwtLR0dEXoDsV5/P5FBEVZ5pZzHdBRCLnvOj/FwCAc74bP4v+EqxJkvQbAAjdG+/GbPOJ"
    "uUD+AgDh7OxsY7Z5xFwkRLQkSdIdgYjWZp1MzMXCOV8TAMRvln4xBEFYmp920bS9vY1cLofH"
    "jx9PdB5jDC9fvsTTp0/hOE5w/PXr16jVasF/y7Kg6zoAIJvNYmtrC7ZtB/ZyuQzTNHviLyws"
    "YHNzE67rAgBKpRIURUEmkwFjDJ7nwXVdGIYBx3GwtbUFx3Hgui5M00S5XA7qSyaTkTiNRmNk"
    "DXt7e6hUKpGcZFmGoijY2dmZqK2mhXN+c/6HXCmEqqpotVpQVRVv3ryJ2PzCE4kEVlZWsL29"
    "HRyzbTv4zRjDw4cPkclkAvF91tfXUSgU4HlecMy/jqZpqNVqsCwLwLcOE4774sUL1Gq1QMBS"
    "qRT4jlODbdvQNK1HWEVRhrbJo0ePcOPGjaE+796965vLIHpeKV42oihiZ2dnaLGe50HXdSST"
    "SWSz2R674zgoFovQNK3HlsvlkEwmp8rNNM2xzh1Ug+u6cBwnkrMsyyMFOTo6Gmo/OTmZSFQA"
    "mOecfyKixVGOjLFIIYwxAIg0rj+9DcIv0nEc2LYNWZZ7eneYVqsFxljfmP6Uet6+t7eHZ8+e"
    "Qdd1GIYRGbmD6vJrYIxFpvv19fVgKvZH9agadF2HqqqBECsrKygUCn07qI/vu7y83GM7OTnB"
    "+/djf4YFABDRp3kiMgEsjnION0CY8LFarTZUWEVR4LouNE2D67pQFGWosOl0emC8RCKBZDLZ"
    "Y69UKjBNE5qmBffBYeJ6nodWqwVFUVAqlSK+/abiUTVYlgVN08AYQzabhWmaIzuXf16r1cLq"
    "6iquX78OYDpRAaDT6ZjznU7nUBCEkY88lmVFFkqTLp4YY2CMBQ3VaDSgqurAEbmwsIBEIgHL"
    "svr2dkVRYBhG32t5nhfc+xRFCRZE/XBdF5VKBbZtY3NzE8+fP//uGnRdh6ZpSCQSKBaLA+Od"
    "p91u4+3bt1hdXUW9Xp9KVAAgosN5IjoAcOlfdFRVRblc7mnk8ALEFzCXy0GWZbx69SrwC99v"
    "/VVuoVDouY4oisH0GRZhFI1GA4ZhQNO0YEGWyWQCu23bY9UA/D9qLcsaa7SGabfbE3WG83DO"
    "zWq1+mGu2Wx+uX379iImfJ5VFAXpdLpnVTqIW7duwTAMfP36NThm2zbS6TTq9TqAb1NvOp2G"
    "67rY399Hu90OfK9duxbYbdvG/v5+JJbP/fv3A79ms9kz1TuOE2ls13WDVXC9Xkculws6QyqV"
    "isRKpVIja/Bj2baNjx8/Rnx922XCOf+z2Wx+IACQJOkOEX2aJIAsyxMJG3P5dDe8LQPR77Hx"
    "R/YrzPmP7XO+odls/jPNlBwze0J7n4JXd3Nhh8+fP/8di3u1GLShrefN0/Hx8Wan01nrnhDz"
    "c3MgCMJiv12K8b7iK8jU+4rDiKL4hIg2YoFnT1fQA875br9RGmaksD6SJN0log3O+VIs8o+j"
    "K+Zhp9M5mJubO/B3IcbExPxK/AfK9QhjjYtInwAAAABJRU5ErkJggg==")
index.append('stream_add_sel')
catalog['stream_add_sel'] = stream_add_sel
getstream_add_selData = stream_add_sel.GetData
getstream_add_selImage = stream_add_sel.GetImage
getstream_add_selBitmap = stream_add_sel.GetBitmap

