name: Self Hosted Runner Ubuntu 20 Unit Testing

on:
  [push, pull_request]
  # schedule:
  #   - cron: "0 22 * * *"  # everyday at 10 pm

jobs:
  full_test:
    runs-on: [self-hosted, Linux]
    steps:
    - name: List of all VMs
      run: VBoxManage list vms

    - name: List of running VMs
      run: VBoxManage list runningvms

    - name: Start Ubuntu 20 VM
      run: |
        VBoxManage startvm "Odemis Testing 20" --type headless
        sleep 1m

    - name: Execute test-cases inside VM
      # The testing user should be automatically be logged in for the display (or the xserver) to be started
      run: VBoxManage --nologo guestcontrol "Odemis Testing 20" run --exe "/home/testing/development/odemis-testing/runpytest_wrapper.sh" --putenv "DISPLAY=:0" --username testing --password delmic --wait-stdout

    - name: Pytest report
      run: VBoxManage --nologo guestcontrol "Odemis Testing 20" run --exe "/bin/bash" --username testing --password delmic --wait-stdout -- bash -c 'cat $(ls -Art /home/testing/development/odemis-testing/pytest-summary-*.log | tail -n 1)'

    - name: Unittest report
      run: VBoxManage --nologo guestcontrol "Odemis Testing 20" run --exe "/bin/bash" --username testing --password delmic --wait-stdout -- bash -c 'cat $(ls -Art /home/testing/development/odemis-testing/unittest-full-*.log | tail -n 1)'

    - name: Stop the VM
      run: VBoxManage controlvm "Odemis Testing 20" poweroff
