name: size-label

on: pull_request_target

jobs:
  size-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.5.7"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

        with:
          # Philosophy: S should be reviewable in under 10 minutes, L takes more than an hour
          sizes: >
            {
              "0": "S",
              "25": "M",
              "400": "L"
            }
